Repository langfuse/langfuse-docs, pull requests merged in 2024-11, with the labels that each got.

#980 docs: new integration section
  components/home/IntegrationsGrid.tsx
  components/home/img/bedrock_icon.png
  components/home/img/dify_icon.png
  components/home/img/dspy_icon.png
  components/home/img/flowise_logo.png
  components/home/img/instructor_icon.svg
  components/home/img/langchain_icon.png
  components/home/img/langflow_icon.svg
  components/home/img/langgraph_icon.png
  components/home/img/mirascope_icon.svg
  components/home/img/ollama_icon.png
  components/home/img/openwebui_icon.png
  components/home/index.tsx
  tailwind.config.js
Labels: documentation, size:L

#982 chore: bump minor deps
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS

#917 Updated Ragas Cookbook
  cookbook/evaluation_of_rag_with_ragas.ipynb
  pages/docs/integrations/llama-index/example-python-instrumentation-module.md
  pages/guides/cookbook/evaluation_of_rag_with_ragas.md
Labels: lgtm, size:M

#976 docs: lw2-0
  components/changelog/ChangelogHeader.tsx
  components/changelog/ChangelogIndex.tsx
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/changelog/2024-04-21-openai-integration-JS-SDK.mdx
  pages/changelog/2024-04-22-posthog-integration.mdx
  pages/changelog/2024-04-23-prompt-playground.mdx
  pages/changelog/2024-04-24-decorator.mdx
  pages/changelog/2024-04-25-datasets-v2.mdx
  pages/changelog/2024-04-26-model-based-evaluation.mdx
  pages/changelog/2024-11-17-vercel-ai-sdk-prompt-mgmt.mdx
  pages/docs/prompts/get-started.mdx
  public/images/changelog/2024-11-17-vercel-ai-sdk-prompt-mgmt/og.png
  public/images/changelog/2024-11-17-vercel-ai-sdk-prompt-mgmt/trace.png
Labels: size:L

#969 docs: add launch week day 0 banner
  theme.config.tsx
Labels: documentation, size:S

#983 docs: new `/docs` page
  components-mdx/evaluation-overview-gifs.mdx
  components-mdx/prompt-overview-gifs.mdx
  components-mdx/tracing-overview-gifs.mdx
  components/Video.tsx
  pages/docs/index.mdx
  pages/docs/prompts/get-started.mdx
  pages/docs/scores/overview.mdx
  pages/docs/tracing.mdx
  src/overrides.css
Labels: docs, size:XL

#984 feat: generate llms.txt based on sitemap
  .gitignore
  package.json
  pnpm-lock.yaml
  scripts/generate_llms_txt.js
Labels: enhancement, size:L

#896 chore: update pricing page
  components/home/Pricing.tsx
  pages/_meta.tsx
  pages/enterprise.mdx
  pages/pricing-self-host.mdx
Labels: size:XL

#986 docs: move releases and versions into tracing-features
  next.config.mjs
  pages/blog/2024-10-observability-in-multi-step-llm-systems.mdx
  pages/docs/_meta.tsx
  pages/docs/get-started.mdx
  pages/docs/integrations/langchain/tracing.mdx
  pages/docs/integrations/llama-index/deprecated-llama-index-callback.mdx
  pages/docs/integrations/llama-index/get-started.mdx
  pages/docs/prompts/get-started.mdx
  pages/docs/tracing-features/_meta.tsx
  pages/docs/tracing-features/releases-and-versioning.mdx
  pages/docs/tracing.mdx
Labels: documentation, size:L

#985 docs(dataset-compare-view): changelog post
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/changelog/2024-11-18-dataset-runs-comparison-view.mdx
  pages/docs/datasets/overview.mdx
  public/images/changelog/2024-11-18-dataset-runs-comparison-view/og.png
  theme.config.tsx
Labels: docs, size:M

#987 docs: update datasets section
  components-mdx/datasets-overview-gif.mdx
  pages/docs/datasets/_meta.tsx
  pages/docs/datasets/get-started.mdx
  pages/docs/datasets/overview.mdx
  pages/docs/index.mdx
Labels: docs, size:XL

#988 feat: add dedicated Clickhouse component docs
  pages/docs/deployment/v3/_meta.tsx
  pages/docs/deployment/v3/components/_meta.tsx
  pages/docs/deployment/v3/components/blobstorage.mdx
  pages/docs/deployment/v3/components/clickhouse.mdx
  pages/docs/deployment/v3/components/redis.mdx
  pages/docs/deployment/v3/migrate-v2-to-v3.mdx
  pages/docs/deployment/v3/overview.mdx
Labels: documentation, size:L

#992 chore: enable background migrations for pg->ch move
  pages/docs/deployment/v3/migrate-v2-to-v3.mdx
Labels: documentation, size:XS

#997 chore: fix broken link in v2 to v3 migration guide
  pages/docs/deployment/v3/migrate-v2-to-v3.mdx
Labels: documentation, size:XS

#999 docs(media): add how it works details
  pages/docs/tracing-features/multi-modality.mdx
Labels: size:M

#1001 feat: add s3 blob store docs
  pages/docs/deployment/v3/components/_meta.tsx
  pages/docs/deployment/v3/components/blobstorage.mdx
  pages/docs/deployment/v3/components/clickhouse.mdx
  pages/docs/deployment/v3/overview.mdx
Labels: documentation, size:L

#1002 feat: add troubleshooting guide outline
  pages/docs/deployment/v3/_meta.tsx
  pages/docs/deployment/v3/troubleshooting.mdx
Labels: documentation, size:M

#1000 docs: Launch Week 2 Day 4 changelog post
  components-mdx/datasets-overview-gif.mdx
  components-mdx/evaluation-overview-gifs.mdx
  components-mdx/prompt-overview-gifs.mdx
  components-mdx/tracing-overview-gifs.mdx
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/changelog/2024-11-21-all-new-datasets-and-evals-documentation.mdx
  pages/docs/index.mdx
  public/images/changelog/2024-11-21-documentation-update/repos.png
  theme.config.tsx
Labels: documentation, size:L

#1007 docs: add image to changelog
  pages/changelog/2024-11-21-all-new-datasets-and-evals-documentation.mdx
  public/images/changelog/2024-11-21-new-documentation.png
Labels: docs, size:XS

#1006 docs: add changelog and docs for launch week day 5
  components-mdx/datasets-create-dataset-item.mdx
  components-mdx/datasets-create-dataset.mdx
  components-mdx/prompt-create.mdx
  components/home/Pricing.tsx
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/changelog/2024-11-22-prompt-experimentation.mdx
  pages/docs/datasets/_meta.tsx
  pages/docs/datasets/get-started.mdx
  pages/docs/datasets/prompt-experiments.mdx
  pages/docs/prompts/_meta.tsx
  pages/docs/prompts/get-started.mdx
  public/images/docs/prompt-experiments-new-experiment.png
Labels: docs, size:XL

#1005 feat: add PH banner and update /ph link
  next.config.mjs
  public/images/producthunt-white.png
  theme.config.tsx
Labels: enhancement, size:S

#1010 docs(media): add update upload status to cookbook
  cookbook/example_multi_modal_traces.ipynb
  pages/guides/cookbook/example_multi_modal_traces.md
Labels: size:M

#1013 feat: azure blob storage docs
  pages/docs/deployment/v3/components/blobstorage.mdx
Labels: documentation, size:S

#1014 docs(vercel): nested executions within parent trace
  pages/docs/integrations/vercel-ai-sdk.mdx
  public/images/docs/vercel-nested-trace.png
Labels: docs, size:M

#1016 docs: add lobechat integration
  pages/cn.mdx
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/lobechat.mdx
  pages/docs/integrations/overview.mdx
  public/images/docs/lobechat-converstation.png
  public/images/docs/lobechat-docker-desktop-env.png
  public/images/docs/lobechat-example-trace.png
  public/images/docs/lobechat-settings.png
Labels: docs, lgtm, size:M

#1019 docs: add sticker link to asian pages
  pages/cn.mdx
  pages/jp.mdx
  pages/kr.mdx
Labels: documentation, size:XS

#1020 feat: add ci pipeline
  .github/workflows/ci.yml
Labels: enhancement, size:S

#1021 docs: add ai agent observability blog post
  pages/blog/2024-07-ai-agent-observability-with-langfuse.mdx
Labels: docs, size:L

#1026 fix: exclude prereleases from latest release api
  pages/api/latest-releases.ts
Labels: size:XS

#1029 docs: add notebook querying via sdks
  cookbook/_routes.json
  cookbook/example_query_data_via_sdk.ipynb
  pages/docs/query-traces.mdx
  pages/guides/cookbook/example_query_data_via_sdk.md
Labels: docs, size:XL

#1031 chore: default to ai chat in inkeep
  components/inkeep/useInkeepSettings.ts
Labels: size:XS

#1030 feat: add posthog tracking to inkeep + prepare for support handover
  components/inkeep/useInkeepSettings.ts
Labels: enhancement, size:M

#1032 chore: bump langufse
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS

#1033 feat: embedded inkeep + share link
  components/inkeep/InkeepChatButton.tsx
  components/inkeep/InkeepEmbeddedChat.tsx
  components/inkeep/InkeepSearchBar.tsx
  components/inkeep/useInkeepSettings.ts
  pages/docs/_meta.tsx
  pages/docs/ask-ai.mdx
  pages/support.mdx
Labels: documentation, enhancement, size:L

#1035 chore: improve inkeep to support handover
  components/inkeep/useInkeepSettings.ts
Labels: size:M

#1036 docs: remove bullets from ask ai
  pages/docs/ask-ai.mdx
Labels: docs, size:XS

#1028 docs: add gemini support via vertex ai platform
  pages/changelog/2024-11-28-google-vertex-ai-support-playground-evals.mdx
  pages/docs/playground.mdx
  public/images/changelog/2024-11-28-google-vertex-support.png
Labels: docs, size:M

#1040 feat: log inkeep question content
  components/inkeep/useInkeepSettings.ts
Labels: enhancement, size:XS

#1041 docs: fix broken links
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/docs/deployment/v3/migrate-v2-to-v3.mdx
  pages/faq/all/ai-research-assistant-monitoring.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
Labels: docs, size:S

#1042 docs: refer to v3 for self-host availability
  components/home/Pricing.tsx
Labels: docs, size:S

#1043 fix: pricing page compliance link
  components/home/Pricing.tsx
Labels: bug, size:XS
