Repository langfuse/langfuse-docs, pull requests merged in 2024-12, with the labels that each got.

#1050 docs: add serveless faq
  pages/faq/all/aws-lambda-and-serverless-functions.mdx
Labels: docs, size:S

#1051 docs: add inkeep link to asia pages and add localized images
  pages/cn.mdx
  pages/jp.mdx
  pages/kr.mdx
  public/images/docs/chinese-example-trace.png
  public/images/docs/japanese-trace-example.png
  public/images/docs/korean-example-trace.png
Labels: documentation, size:S

#1052 docs: add dependents table (python sdk)
  components-mdx/dependents/README.md
  components-mdx/dependents/python.md
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/faq/all/packages-depending-on-langfuse.mdx
  pyproject.toml
  scripts/update_package_usage.sh
Labels: docs, size:L

#1044 chore: update env vars for v3 guide
  pages/docs/deployment/v3/components/blobstorage.mdx
  pages/docs/deployment/v3/guides/docker-compose.mdx
  pages/docs/deployment/v3/overview.mdx
Labels: documentation, size:L

#1056 docs: add google tracing notebook
  components-mdx/dependents/python.md
  cookbook/_routes.json
  cookbook/integration_amazon_bedrock.ipynb
  cookbook/integration_google_vertex_and_gemini.ipynb
  pages/changelog/2024-12-02-tracing-docs-for-google-vertex-ai-and-gemini.mdx
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/amazon-bedrock.md
  pages/docs/integrations/google-vertex-ai.md
  pages/guides/cookbook/integration_amazon_bedrock.md
  pages/guides/cookbook/integration_google_vertex_and_gemini.md
Labels: docs, size:XL

#1057 fix: notebook js readme
  cookbook/README.md
Labels: documentation, size:XS

#1059 feat: add 404 animation
  components/not-found-animation.tsx
  next-env.d.ts
  package.json
  pages/404.mdx
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement, size:L

#1060 docs: add deno.json
  cookbook/deno.json
Labels: docs, size:XS

#1061 fix: add git checkout v2 to local run docs
  pages/docs/deployment/local.mdx
Labels: docs, size:XS

#1062 docs: add community hour banner
  theme.config.tsx
Labels: docs, size:M

#1064 docs: edit banner
  theme.config.tsx
Labels: docs, size:XS

#1067 docs: add example notebook for the JS SDK
  components-mdx/get-started-js-sdk.mdx
  cookbook/_routes.json
  cookbook/js_langfuse_sdk.ipynb
  pages/changelog/2024-12-04-extensive-end-to-end-example-for-js-ts.mdx
  pages/docs/get-started.mdx
  pages/docs/sdk/python/decorators.mdx
  pages/docs/sdk/typescript/_meta.tsx
  pages/docs/sdk/typescript/example-notebook.md
  pages/docs/sdk/typescript/guide.mdx
  pages/guides/cookbook/js_langfuse_sdk.md
Labels: documentation, lgtm, size:XXL

#1071 docs: add google to landingpage integrations
  components/home/IntegrationsGrid.tsx
  components/home/img/google_gemini.svg
Labels: docs, size:M

#1072 feat: add search via inkeep in addition to ask ai, default for search bar
  components/inkeep/InkeepSearchBar.tsx
  components/inkeep/useInkeepSettings.ts
Labels: enhancement, size:XS

#1074 chore: improve wording and typos in V3 docs
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/docs/deployment/_meta.tsx
  pages/docs/deployment/self-host.mdx
  pages/docs/deployment/v3/components/clickhouse.mdx
  pages/docs/deployment/v3/guides/docker-compose.mdx
  pages/docs/deployment/v3/guides/kubernetes-helm.mdx
  pages/docs/deployment/v3/migrate-v2-to-v3.mdx
  pages/docs/deployment/v3/overview.mdx
  pages/docs/deployment/v3/troubleshooting.mdx
  pages/faq/all/api-limits.mdx
Labels: documentation, size:M

#1075 feat: add clickhouse and s3 backup context
  pages/docs/deployment/v3/components/blobstorage.mdx
  pages/docs/deployment/v3/components/clickhouse.mdx
Labels: documentation, size:S

#1054 docs: community page
  pages/_meta.tsx
  pages/community.mdx
  public/images/docs/langfuse-community.png
Labels: documentation, lgtm, size:M

#1079 fix(ui): animation rotation
  components/not-found-animation.tsx
  pages/404.mdx
Labels: size:S

#1078 chore(ui): add border to tab content
  theme.config.tsx
Labels: size:XS

#1083 docs: add hack night challenge overview
  pages/_meta.tsx
  pages/hacknight2024.mdx
Labels: docs, size:L

#1084 docs: add hacknight
  pages/_meta.tsx
  pages/events/_meta.tsx
  pages/events/hacknight2024.mdx
Labels: documentation, size:S

#1085 feat: add icons to logo context menu and fix Firefox compatibility issue
  components/LogoContextMenu.tsx
  public/langfuse_icon.png
  public/langfuse_icon.svg
  public/langfuse_logo.png
Labels: enhancement, size:M

#1081 feat: update kubernetes helm to released version
  next-env.d.ts
  pages/self-hosting/kubernetes-helm.mdx
Labels: documentation, size:M

#1086 docs: add vapi images
  public/images/docs/vapi-integration-credentials.png
  public/images/docs/vapi-integration-example-trace.png
Labels: docs, size:XS

#1082 docs: add vapi integration
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/vapi.mdx
  pages/docs/integrations/overview.mdx
Labels: docs, size:M

#1073 docs: Add Inferable as an integration
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/inferable.mdx
  pages/docs/integrations/overview.mdx
  public/images/docs/inferable-langfuse-eval.png
  public/images/docs/inferable-langfuse-trace.png
Labels: documentation, size:L

#1088 docs: add gradio notebook
  cookbook/_routes.json
  cookbook/integration_gradio_chatbot.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/gradio.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_gradio_chatbot.md
Labels: documentation, size:XL

#1089 docs: add blog post to /jp
  pages/jp.mdx
Labels: docs, size:XS

#1093 chore: bump next 15.1
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS

#1094 docs(media): add section resolving reference strings
  next-env.d.ts
  pages/docs/tracing-features/multi-modality.mdx
Labels: docs, size:M

#1101 feat: update docs for posthog integration
  pages/docs/analytics/posthog.mdx
Labels: documentation, size:S

#1105 fix: fix broken link to upgrade guides
  pages/self-hosting/v2/index.mdx
Labels: size:XS

#1099 docs: add jp video
  pages/jp.mdx
Labels: docs, size:XS

#1106 feat: add dependency tracking for js sdk
  components-mdx/dependents/js.md
  components-mdx/dependents/python.md
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/faq/all/packages-depending-on-langfuse.mdx
  scripts/update_package_usage.sh
Labels: enhancement, size:L

#1107 feat: add inkeep chat to faq overview page
  components/inkeep/useInkeepSettings.ts
  pages/faq/index.mdx
  pages/support.mdx
Labels: enhancement, size:S

#1109 chore: add note on zero-donwtime background migrations
  next-env.d.ts
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: documentation, size:S

#1110 docs: add v3 blog post
  next-env.d.ts
  pages/blog/2024-12-langfuse-v3-infrastructure-evolution.mdx
  public/images/blog/2024-12-langfuse-v3-infrastructure-evolution/og.png
  public/images/blog/2024-12-langfuse-v3-infrastructure-evolution/query-performance.png
Labels: docs, size:L

#1114 chore: increase rate-limits
  pages/faq/all/api-limits.mdx
Labels: size:XS

#1115 enable banner
  theme.config.tsx
Labels: enhancement, size:M

#1127 docs: link fixes
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/faq/all/ai-research-assistant-monitoring.mdx
  pages/faq/all/best-helicone-alternative.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/faq/all/custom-langchain-run-names.mdx
  pages/faq/all/monitoring-ai-generated-content.mdx
  pages/self-hosting/infrastructure/containers.mdx
  pages/self-hosting/v2/docker-compose.mdx
Labels: docs, size:M

#1130 docs: add hugging face gradio template link to docs
  cookbook/integration_gradio_chatbot.ipynb
  pages/docs/integrations/other/gradio.md
  pages/guides/cookbook/integration_gradio_chatbot.md
Labels: documentation, size:XS

#1128 docs: exclude /events from the sitemap
  next-sitemap.config.js
Labels: docs, lgtm, size:XS

#1131 docs: move minio media upload troubleshooting to s3 guide
  pages/self-hosting/docker-compose.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: docs, size:S

#1132 fix: show controls for gif in docs
  components/Video.tsx
Labels: documentation, size:XS

#1133 chore: upgrade vidstack
  components/Video.tsx
  package.json
  pages/_app.tsx
  pnpm-lock.yaml
Labels: dependencies, size:M
