Repository langfuse/langfuse-docs, pull requests merged in 2025-06, with the labels that each got.

#1590 docs: update self host pro tier
  components/availability.tsx
  components/home/Pricing.tsx
  pages/docs/analytics/integrations/posthog.mdx
  pages/docs/datasets/prompt-experiments.mdx
  pages/docs/playground.mdx
  pages/docs/query-traces.mdx
  pages/docs/scores/annotation.mdx
  pages/docs/scores/model-based-evals.mdx
  pages/self-hosting/license-key.mdx
Labels: documentation, size:L, auto-merge

#1598 feat: added simple CTA at bottom of home page - promting visitor to get started
  components/home/CTASocial.tsx
  components/home/index.tsx
Labels: enhancement, size:M, auto-merge

#1599 chore: add otel collector example redirect
  next.config.mjs
Labels: size:XS, auto-merge

#1600 chore: document stuck migration fixes
  pages/self-hosting/background-migrations.mdx
Labels: documentation, size:S, auto-merge

#1601 chore: add config note on log header propagation
  pages/self-hosting/configuration.mdx
Labels: documentation, size:XS, auto-merge

#1603 feat: enhance custom dashboard docs
  pages/docs/analytics/custom-dashboards.mdx
Labels: documentation, size:L, auto-merge

#1604 docs: open sourcing pro features
  components/Authors.tsx
  pages/blog/2025-06-04-open-sourcing-langfuse-product.mdx
  pages/changelog/2025-06-04-open-sourcing-langfuse.mdx
  public/images/blog/2025-06-04-open-sourcing-langfuse-product/change-visual.png
  public/images/blog/2025-06-04-open-sourcing-langfuse-product/langfuse-open-source-og.png
Labels: documentation, size:L, auto-merge

#1605 docs: add new security researcher contribution for hyperlink injection
  pages/security/responsible-disclosure.mdx
Labels: docs, size:XS, auto-merge

#1610 feat: add self-hosted backup guide
  pages/self-hosting/_meta.tsx
  pages/self-hosting/backups.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
  pages/self-hosting/infrastructure/clickhouse.mdx
Labels: documentation, size:L, auto-merge

#1613 docs: update integration pages: Pydantic AI
  cookbook/integration_aws_strands_agents.ipynb
  cookbook/integration_dspy.ipynb
  cookbook/integration_pydantic_ai.ipynb
  pages/docs/integrations/dspy.md
  pages/docs/integrations/dspy.mdx
  pages/docs/integrations/pydantic-ai.md
  pages/docs/integrations/pydantic-ai.mdx
  pages/docs/integrations/strands-agents.md
  pages/guides/cookbook/integration_aws_strands_agents.md
  pages/guides/cookbook/integration_dspy.md
  pages/guides/cookbook/integration_dspy.mdx
  pages/guides/cookbook/integration_pydantic_ai.md
  pages/guides/cookbook/integration_pydantic_ai.mdx
  public/images/cookbook/integration-dspy/dspy-example-trace.png
  public/images/cookbook/otel-integration-pydantic-ai/pydanticai-openai-trace-tree.png
Labels: documentation, size:XXL, auto-merge

#1621 feat: add changelog entry for OpenAI o3-pro support and updated pricing
  pages/changelog/2025-06-10-o3-pro-support.mdx
Labels: documentation, size:S, auto-merge

#1622 Update LiteLLM integration docs
  pages/docs/integrations/litellm/tracing.mdx
Labels: documentation, size:S, auto-merge, codex

#1623 Remove availability banners for OSS features
  pages/docs/analytics/custom-dashboards.mdx
  pages/docs/analytics/integrations/posthog.mdx
  pages/docs/data-deletion.mdx
  pages/docs/datasets/prompt-experiments.mdx
  pages/docs/opentelemetry/get-started.mdx
  pages/docs/playground.mdx
  pages/docs/scores/annotation.mdx
  pages/docs/scores/custom.mdx
  pages/docs/scores/model-based-evals.mdx
Labels: documentation, size:M, auto-merge, codex

#1625 Spell check latest blog posts
  pages/blog/2025-03-31-langfuse-march-update.mdx
Labels: documentation, size:S, auto-merge

#1626 chore: simplify docs footer feedback
  components/MainContentWrapper.tsx
Labels: documentation, size:L, auto-merge

#1618 docs: update langgraph
  components-mdx/integration-notebooks-features.mdx
  cookbook/example_langgraph_agents.ipynb
  cookbook/integration_langgraph.ipynb
  pages/docs/integrations/langchain/example-langgraph-agents.mdx
  pages/docs/integrations/langchain/example-python-langgraph.mdx
  pages/guides/cookbook/example_langgraph_agents.mdx
  pages/guides/cookbook/integration_langgraph.mdx
Labels: documentation, size:XXL, auto-merge

#1628 docs: update llamaindex parts
  cookbook/integration_databricks.ipynb
  pages/docs/integrations/databricks/example-python.md
  pages/docs/tracing-features/environments.mdx
  pages/docs/tracing-features/masking.mdx
  pages/docs/tracing-features/metadata.mdx
  pages/docs/tracing-features/sampling.mdx
  pages/docs/tracing-features/sessions.mdx
  pages/docs/tracing-features/tags.mdx
  pages/docs/tracing-features/users.mdx
  pages/guides/cookbook/integration_databricks.md
Labels: size:L, auto-merge

#1630 docs: update blog post with new agent frameworks
  pages/blog/2025-03-19-ai-agent-comparison.mdx
Labels: size:M, auto-merge

#1631 docs: change image
  public/images/people/team.jpg
Labels: size:XS, auto-merge

#1632 chore: update Cal.com scheduling links for US and EU regions
  components/CalComScheduleDemo.tsx
Labels: size:XS, auto-merge

#1633 docs: update misc integrations
  cookbook/example_multi_modal_traces.ipynb
  cookbook/integration_agno_agents.ipynb
  cookbook/integration_langchain.ipynb
  cookbook/integration_smolagents.ipynb
  pages/changelog/2025-03-17-openai-response-api-support.mdx
  pages/docs/integrations/langchain/example-python.md
  pages/docs/integrations/langchain/upgrade-paths.mdx
  pages/docs/integrations/other/agno-agents.md
  pages/docs/integrations/smolagents.md
  pages/guides/cookbook/example_multi_modal_traces.md
  pages/guides/cookbook/integration_agno_agents.md
  pages/guides/cookbook/integration_langchain.md
  pages/guides/cookbook/integration_smolagents.md
  public/images/cookbook/integration_langchain/langchain_LCEL.png
  public/images/cookbook/integration_langchain/langchain_qa_retrieval.png
  public/images/docs/langchain_LCEL.png
  public/images/docs/langchain_qa_retrieval.jpg
Labels: documentation, size:XXL, auto-merge

#1637 fix: replace Yelp with PwC in customer story
  pages/customers/magic-patterns-ai-design-tools.mdx
Labels: documentation, size:XS, auto-merge

#1639 docs: Improve prompt experiment documentation clarity
  pages/docs/datasets/prompt-experiments.mdx
  public/images/docs/prompt-experiments-new-experiment.png
Labels: documentation, size:M, auto-merge

#1641 docs: add cost cutting faq page
  components/home/Pricing.tsx
  pages/faq/all/cutting-costs.mdx
Labels: docs, size:M, auto-merge

#1644 Update roadmap.mdx
  pages/docs/roadmap.mdx
Labels: documentation, size:S, auto-merge

#1645 docs: revamp /docs
  components/FeatureOverview.tsx
  components/home/FeatureBento.tsx
  pages/docs/_meta.tsx
  pages/docs/core-features.mdx
  pages/docs/index.mdx
  pages/faq/all/challenges-of-building-llm-applications.mdx
  pages/why.mdx
  public/images/docs/features-dark.png
  public/images/docs/features-light.png
Labels: docs, size:L, auto-merge

#1652 feat: add Redis Cluster documentation
  pages/self-hosting/configuration.mdx
  pages/self-hosting/infrastructure/cache.mdx
  pages/self-hosting/scaling.mdx
Labels: documentation, size:L

#1659 fix: fix json import and lack of envs on older versions
  cookbook/example_data_migration.ipynb
Labels: size:XS

#1642 Fix Typos in Security Example and Authentication Documentation
  cookbook/example_llm_security_monitoring.ipynb
  pages/docs/security/example-python.md
  pages/self-hosting/authentication-and-sso.mdx
Labels: documentation, size:XS

#1638 Trace IDs & Distributed Tracing: Add missing context to the Langchain (JS/TS) usage example
  pages/docs/tracing-features/trace-ids.mdx
Labels: documentation, size:XS

#1664 docs: misc changes
  cookbook/integration_amazon_bedrock.ipynb
  cookbook/integration_google_vertex_and_gemini.ipynb
  pages/docs/integrations/bedrock/amazon-bedrock.md
  pages/docs/integrations/google-vertex-ai.md
  pages/guides/cookbook/integration_amazon_bedrock.md
  pages/guides/cookbook/integration_google_vertex_and_gemini.md
Labels: docs, size:S, auto-merge

#1667 feat: tracing data model docs page overhaul
  pages/docs/tracing-data-model.mdx
  public/images/docs/tracing-observation-tree-dark.png
  public/images/docs/tracing-observation-tree-light.png
  src/overrides.css
  tailwind.config.js
Labels: documentation, size:M, auto-merge

#1670 fix: Correct typos in model-based evaluation docs
  pages/changelog/2024-04-26-model-based-evaluation.mdx
Labels: documentation, size:XS

#1673 chore: add recommendations on bucket settings for S3 clickhouse disks
  pages/self-hosting/infrastructure/clickhouse.mdx
Labels: documentation, size:S, auto-merge

#1665 chore: add graduated pricing to pricing page
  components/home/Pricing.tsx
  pages/docs/tracing-data-model.mdx
  pages/faq/all/cutting-costs.mdx
Labels: enhancement, size:L, auto-merge

#1676 docs: refine tracing data model section and enhance FAQ formatting
  pages/docs/tracing-data-model.mdx
Labels: documentation, size:S, auto-merge

#1677 feat: add calculatorOpen flag to pricing page
  components/home/Pricing.tsx
  pages/docs/tracing-data-model.mdx
  pages/faq/all/cutting-costs.mdx
Labels: documentation, enhancement, size:S, auto-merge

#1682 chore: fix unit calculation and add teams tier to pricing calculator
  components/home/Pricing.tsx
Labels: size:XS, auto-merge

#1683 chore: prioritize ask ai
  components/MainContentWrapper.tsx
  components/supportChat/index.tsx
  pages/support.mdx
Labels: size:M, auto-merge

#1684 feat: Persist GitHub stars at build time
  components/GitHubBadge.tsx
  components/home/Usage.tsx
  lib/github-stars.ts
  package.json
  pages/api/stargazer-count.ts
  scripts/update-github-stars.js
  src/github-stars.ts
Labels: enhancement, size:L

#1685 remove careers@ email link ot reduce mail applications
  pages/about.mdx
Labels: documentation, size:XS, auto-merge

#1687 update mcp docs for cursor
  pages/docs/prompts/mcp-server.mdx
Labels: documentation, size:M, auto-merge

#1672 fix: correct typos in documentation
  cookbook/integration_instructor.ipynb
  cookbook/integration_llama_index_posthog_mistral.ipynb
  pages/docs/integrations/instructor.mdx
  pages/guides/cookbook/integration_instructor.mdx
  pages/guides/cookbook/integration_llama_index_posthog_mistral.md
Labels: documentation, lgtm, size:S

#1688 add rss changelog
  pages/api/changelog-rss.xml.ts
  pages/changelog.mdx
Labels: documentation, size:M, auto-merge

#1690 Add security page link to sidebar
  pages/docs/_meta.tsx
Labels: documentation, size:XS, auto-merge

#1694 Update langchain to langfuse in examples
  pages/docs/scores/user-feedback.mdx
Labels: documentation, size:XS

#1689 fix: Update CallbackHandler import path in LangChain example
  pages/docs/get-started.mdx
Labels: bug, documentation, size:XS

#1696 Remove plus sign from GitHub stars
  components/home/Usage.tsx
Labels: enhancement, size:S, auto-merge

#1695 feat: agentic onboarding
  components-mdx/agentic-tracing-integration.mdx
  components-mdx/docs-mcp-server-installation.mdx
  components/agentic-onboarding/CopyAgentOnboardingPrompt.tsx
  pages/changelog/2025-06-28-agentic-onboarding-and-docs-mcp.mdx
  pages/docs/_meta.tsx
  pages/docs/ask-ai.mdx
  pages/docs/docs-mcp.mdx
  pages/docs/get-started.mdx
  public/images/changelog/2025-06-28-agentic-onboarding-and-docs-mcp.png
  public/images/docs/docs-mcp-example.png
Labels: documentation, enhancement, size:L, auto-merge

#1698 Add Posthog tracking to MCP server
  package.json
  pages/api/mcp.ts
  pnpm-lock.yaml
Labels: size:M

#1700 Add new tool to MCP docs
  pages/docs/docs-mcp.mdx
Labels: documentation, size:XS, auto-merge

#1702 Add Langfuse MCP server integration
  components-mdx/docs-mcp-server-installation.mdx
Labels: size:M, auto-merge

#1703 Update CopyAgentOnboardingPrompt.tsx
  components/agentic-onboarding/CopyAgentOnboardingPrompt.tsx
Labels: size:XS, auto-merge

#1693 Fel/revamp-careers-page
  components/MainContentWrapper.tsx
  components/customers/ImpactChart.tsx
  components/ui/carousel.tsx
  pages/careers.mdx
  public/images/careers/office3.jpg
  public/images/careers/team3.jpg
  public/images/careers/team4.jpg
  public/images/careers/team5.jpg
  public/images/careers/team6.jpg
Labels: documentation, size:L

#1711 Identify and correct documentation typos
  cookbook/integration_llama_index_posthog_mistral.ipynb
  pages/blog/2024-07-ai-agent-observability-with-langfuse.mdx
  pages/blog/2025-06-30-langfuse-june-update.mdx
  pages/docs/analytics/example-intent-classification.md
  pages/docs/integrations/litellm/tracing.mdx
  pages/docs/tracing.mdx
  pages/faq/all/best-helicone-alternative.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
  pages/guides/cookbook/example_intent_classification_pipeline.md
  pages/guides/cookbook/integration_llama_index_posthog_mistral.md
Labels: documentation, size:S, auto-merge

#1713 Update 2025-06-28-agentic-onboarding-and-docs-mcp.mdx
  pages/changelog/2025-06-28-agentic-onboarding-and-docs-mcp.mdx
Labels: documentation, size:XS, auto-merge

#1714 mark mcp as optional
  pages/docs/get-started.mdx
Labels: documentation, size:XS
