Repository langfuse/langfuse-docs, pull requests merged in 2025-09, with the labels that each got.

#2003 docs: add Langfuse August Update
  pages/blog/2025-08-13-evaluating-model-performance-accross-clouds-with-shadeform-and-langfuse.mdx
  pages/blog/2025-08-31-langfuse-august-update.mdx
  public/images/blog/2025-08-31-langfuse-august-update/august-update.png
  public/images/blog/2025-08-31-langfuse-august-update/community-growth.png
  public/images/blog/2025-08-31-langfuse-august-update/demo-project.png
  public/images/blog/2025-08-31-langfuse-august-update/demo-video.png
  public/images/blog/2025-08-31-langfuse-august-update/observation-types.png
Labels: documentation, size:M, auto-merge

#2013 Seo fixies
  components-mdx/docs-mcp-server-installation.mdx
  components-mdx/integration-learn-more.mdx
  cookbook/integration_amazon_bedrock.ipynb
  cookbook/integration_aws_strands_agents.ipynb
  cookbook/integration_pydantic_ai.ipynb
  lib/redirects.js
  pages/blog/2024-04-python-decorator.mdx
  pages/blog/2025-03-19-ai-agent-comparison.mdx
  pages/docs/observability/sdk/python/advanced-usage.mdx
  pages/guides/cookbook/integration_amazon_bedrock.md
  pages/integrations/frameworks/langchain.mdx
  pages/integrations/frameworks/pydantic-ai.mdx
  pages/integrations/frameworks/strands-agents.mdx
  pages/integrations/model-providers/amazon-bedrock.md
  pages/integrations/no-code/flowise.mdx
Labels: documentation, size:M, auto-merge

#2014 docs: reorder guides video
  pages/guides/index.mdx
Labels: documentation, size:S, auto-merge

#2016 Center user bubble text on small screens
  components/home/Pricing.tsx
Labels: bug, size:XS

#2025 fix: make all redirects non-permanent
  lib/redirects.js
  next.config.mjs
  scripts/generate-cloudflare-redirects.js
Labels: bug, size:XXL

#2015 docs: add admin section on sso and troubleshooting
  pages/docs/administration/_meta.tsx
  pages/docs/administration/authentication-and-sso.mdx
  pages/docs/administration/rbac.mdx
  pages/docs/administration/troubleshooting-and-faq.mdx
  pages/faq/all/cannot-see-organization.mdx
  pages/faq/all/delete-account-langfuse.mdx
  pages/faq/all/forgot-password.mdx
  pages/faq/all/inviting-in-langfuse.mdx
  pages/faq/all/limit-access-to-internal-users.mdx
  pages/faq/all/managing-different-environments.mdx
  pages/faq/all/sso-har-file-export.mdx
  pages/faq/all/where-are-langfuse-api-keys.mdx
  pages/faq/all/where-is-my-project.mdx
  pages/security/auth.mdx
  pages/self-hosting/security/authentication-and-sso.mdx
Labels: documentation, size:L

#2024 docs: update openrouter page
  pages/integrations/gateways/openrouter.mdx
  public/images/docs/openrouter-example-trace/openrouter-example-trace.png
Labels: documentation, size:S

#2026 chore: reintroduce permanent redirects
  lib/redirects.js
  next.config.mjs
  scripts/generate-cloudflare-redirects.js
Labels: documentation, size:L, auto-merge

#2030 ci: do not check the /ph link
  scripts/check-links.js
Labels: size:M, auto-merge

#2032 feat: replace tabs with langtabs in mdx files
  components-mdx/datasets-create-dataset-item.mdx
  components-mdx/datasets-create-dataset.mdx
  components-mdx/prompt-create.mdx
  components-mdx/prompt-linking.mdx
  pages/blog/update-2023-09.mdx
  pages/blog/update-2023-10.mdx
  pages/changelog/2023-09-25-datasets.mdx
  pages/changelog/2024-02-05-sdk-level-prompt-caching.mdx
  pages/changelog/2024-07-04-query-traces-via-sdks.mdx
  pages/changelog/2024-07-11-non-numeric-scores-api.mdx
  pages/changelog/2024-09-04-prompt-management-zero-latency.mdx
  pages/changelog/2025-02-05-public-api-wrapper-sdks.mdx
  pages/changelog/2025-03-17-openai-response-api-support.mdx
  pages/docs/administration/data-deletion.mdx
  pages/docs/api-and-data-platform/features/public-api.mdx
  pages/docs/api-and-data-platform/features/query-via-sdk.mdx
  pages/docs/evaluation/dataset-runs/datasets.mdx
  pages/docs/evaluation/dataset-runs/remote-run.mdx
  pages/docs/evaluation/evaluation-methods/custom-scores.mdx
  pages/docs/metrics/features/metrics-api.mdx
  pages/docs/observability/features/comments.mdx
  pages/docs/observability/features/environments.mdx
  pages/docs/observability/features/log-levels.mdx
  pages/docs/observability/features/masking.mdx
  pages/docs/observability/features/metadata.mdx
  pages/docs/observability/features/multi-modality.mdx
  pages/docs/observability/features/observation-types.mdx
  pages/docs/observability/features/queuing-batching.mdx
  pages/docs/observability/features/releases-and-versioning.mdx
  pages/docs/observability/features/sampling.mdx
  pages/docs/observability/features/sessions.mdx
  pages/docs/observability/features/tags.mdx
  pages/docs/observability/features/token-and-cost-tracking.mdx
  pages/docs/observability/features/trace-ids-and-distributed-tracing.mdx
  pages/docs/observability/features/url.mdx
  pages/docs/observability/features/users.mdx
  pages/docs/observability/get-started.mdx
  pages/docs/observability/sdk/typescript/instrumentation.mdx
  pages/docs/prompt-management/features/a-b-testing.mdx
  pages/docs/prompt-management/features/caching.mdx
  pages/docs/prompt-management/features/composability.mdx
  pages/docs/prompt-management/features/guaranteed-availability.mdx
  pages/docs/prompt-management/features/message-placeholders.mdx
  pages/docs/prompt-management/features/prompt-version-control.mdx
  pages/docs/prompt-management/features/webhooks-slack-integrations.mdx
  pages/docs/prompt-management/get-started.mdx
  pages/faq/all/error-handling-and-timeouts.mdx
  pages/integrations/frameworks/langchain.mdx
  pages/integrations/gateways/vercel-ai-gateway.mdx
  pages/integrations/other/promptfoo.mdx
Labels: documentation, size:L, auto-merge

#2037 Fix caching docs link
  pages/changelog/2024-02-05-sdk-level-prompt-caching.mdx
Labels: size:XS

#2033 fix: update example
  pages/integrations/frameworks/vercel-ai-sdk.mdx
Labels: bug, size:XS, auto-merge

#2045 chore: remove license key trial
  pages/faq/all/self-hosting-langfuse.mdx
  pages/self-hosting/administration/organization-creators.mdx
  pages/self-hosting/administration/organization-management-api.mdx
  pages/self-hosting/administration/ui-customization.mdx
  pages/self-hosting/index.mdx
Labels: documentation, size:S, auto-merge

#2057 docs: add automated evaluation guide
  pages/blog/2025-08-29-error-analysis-to-evaluate-llm-applications.mdx
  pages/blog/2025-09-05-automated-evaluations.mdx
  public/images/blog/2025-09-05-automated-evaluations/automated-evaluations.png
  public/images/blog/2025-09-05-automated-evaluations/evaluator-tuning.png
  public/images/blog/2025-09-05-automated-evaluations/prompt.png
  public/images/blog/2025-09-05-automated-evaluations/setup-evaluator.png
Labels: documentation, size:L, auto-merge

#2067 chore(pricing): remove eval count limit from hobby/free plan
  components/home/Pricing.tsx
Labels: size:M

#2073 chore(billing) update pricing of core plan
  components/home/Pricing.tsx
Labels: size:XS, auto-merge

#2071 chore: remove self-host faq question
  components/home/Pricing.tsx
Labels: documentation, size:XS

#2086 fix(research): add bibtex for sso
  pages/research.mdx
Labels: documentation, size:XS, auto-merge

#2087 docs: add note on tool call type obs
  pages/docs/prompt-management/features/playground.mdx
Labels: documentation, size:XS, auto-merge

#2093 Dataset csv upload clarification
  components-mdx/datasets-create-dataset-item.mdx
  pages/docs/evaluation/experiments/datasets.mdx
Labels: documentation, size:XS, auto-merge

#2095 feat: add customer carousel to home
  components/customers/CustomerCarousel.tsx
  components/home/CustomerStories.tsx
  components/home/index.tsx
  pages/customers/khan-academy.mdx
  pages/customers/magic-patterns-ai-design-tools.mdx
  pages/customers/merckgroup.mdx
  pages/customers/sumup.mdx
Labels: enhancement, size:L, auto-merge

#2097 chore: watch demo as cta in hero
  components/home/Hero.tsx
Labels: size:XS, auto-merge

#2044 feat: publish /handbook
  components-mdx/handbook/principles.mdx
  components/MainContentWrapper.tsx
  components/handbook/ChapterIndex.tsx
  components/handbook/TeamsIndex.tsx
  components/home/Usage.tsx
  cookbook/example_evaluating_openai_agents.ipynb
  cookbook/example_langgraph_agents.ipynb
  cookbook/js_integration_openai.ipynb
  lib/redirects.js
  pages/_meta.tsx
  pages/careers.mdx
  pages/changelog/2024-02-27-llama-index-integration.mdx
  pages/docs/administration/llm-connection.mdx
  pages/docs/api-and-data-platform/features/query-via-sdk.mdx
  pages/guides/cookbook/example_evaluating_openai_agents.md
  pages/guides/cookbook/example_langgraph_agents.mdx
  pages/guides/cookbook/js_integration_openai.mdx
  pages/handbook/_meta.tsx
  pages/handbook/chapters/_meta.tsx
  pages/handbook/chapters/customers.mdx
  pages/handbook/chapters/monetization.mdx
  pages/handbook/chapters/open-source.mdx
  pages/handbook/chapters/team.mdx
  pages/handbook/chapters/why.mdx
  pages/handbook/gtm/_meta.tsx
  pages/handbook/gtm/customer-success.mdx
  pages/handbook/gtm/overview.mdx
  pages/handbook/gtm/sales.mdx
  pages/handbook/gtm/support.mdx
  pages/handbook/index.mdx
  pages/handbook/operations/entity-structure.mdx
  pages/handbook/operations/finance.mdx
  pages/handbook/product-engineering/documentation.mdx
  pages/handbook/product-engineering/principles.mdx
  pages/handbook/product-engineering/product-ops.mdx
  pages/handbook/product-engineering/releases.mdx
  pages/handbook/product-engineering/roadmapping.mdx
  pages/handbook/working-at-langfuse/_meta.tsx
  pages/handbook/working-at-langfuse/how-we-work/culture.mdx
  pages/handbook/working-at-langfuse/how-we-work/meetings.mdx
  pages/handbook/working-at-langfuse/how-we-work/ownership.mdx
  pages/handbook/working-at-langfuse/how-we-work/personal-productivity.mdx
  pages/handbook/working-at-langfuse/how-we-work/use-ai.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-linear.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-plain.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-slack.mdx
  pages/handbook/working-at-langfuse/principles.mdx
  pages/handbook/working-at-langfuse/spending-money.mdx
  pages/handbook/working-at-langfuse/time-off.mdx
  pages/research.mdx
  public/images/handbook/using-plain/plain-screenshot.png
  scripts/check-links.js
  src/overrides.css
  theme.config.tsx
Labels: documentation, size:XL, auto-merge

#2106 Deduplicate handbook meta paths and pages
  components/handbook/TeamsIndex.tsx
  pages/handbook/_meta.tsx
Labels: enhancement, size:M, auto-merge

#2109 feat: add new landingpage feature component
  components/ai-elements/code-block.tsx
  components/home/FeatureTabsSection.tsx
  components/home/Hero.tsx
  components/home/Usage.tsx
  components/home/feature-tabs/FeatureTabs.tsx
  components/home/feature-tabs/TabButton.tsx
  components/home/feature-tabs/TabContent.tsx
  components/home/feature-tabs/data.ts
  components/home/feature-tabs/img/Annotation.png
  components/home/feature-tabs/img/cost.png
  components/home/feature-tabs/img/evals-wide.png
  components/home/feature-tabs/img/evals.png
  components/home/feature-tabs/img/metrics.png
  components/home/feature-tabs/img/observability-2.png
  components/home/feature-tabs/img/observability.png
  components/home/feature-tabs/img/playground.png
  components/home/feature-tabs/img/prompt.png
  components/home/feature-tabs/index.ts
  components/home/feature-tabs/types.ts
  components/home/img/feature_tracing.png
  components/home/img/feature_tracing_2.png
  components/home/index.tsx
  data/generated/contributors.json
  src/github-stars.ts
  tsconfig.tsbuildinfo
Labels: enhancement, size:XXL, auto-merge

#2107 Proofread and correct handbook mdx files
  pages/handbook/chapters/customers.mdx
  pages/handbook/chapters/monetization.mdx
  pages/handbook/chapters/team.mdx
  pages/handbook/gtm/customer-success.mdx
  pages/handbook/gtm/sales.mdx
  pages/handbook/gtm/support.mdx
  pages/handbook/product-engineering/documentation.mdx
  pages/handbook/product-engineering/principles.mdx
  pages/handbook/product-engineering/releases.mdx
  pages/handbook/working-at-langfuse/how-we-work/culture.mdx
  pages/handbook/working-at-langfuse/how-we-work/meetings.mdx
  pages/handbook/working-at-langfuse/how-we-work/personal-productivity.mdx
  pages/handbook/working-at-langfuse/how-we-work/use-ai.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-linear.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-plain.mdx
  pages/handbook/working-at-langfuse/how-we-work/using-slack.mdx
  pages/handbook/working-at-langfuse/principles.mdx
  pages/handbook/working-at-langfuse/spending-money.mdx
  pages/handbook/working-at-langfuse/time-off.mdx
Labels: size:L

#2115 docs: update n+1 guide
  cookbook/example_evaluating_multi_turn_conversations.ipynb
  pages/guides/cookbook/example_evaluating_multi_turn_conversations.mdx
Labels: documentation, size:S, auto-merge

#2120 feat:split-out-quickstarts-in-docs-nav
  pages/docs/_meta.tsx
  pages/docs/evaluation/evaluation-methods/llm-as-a-judge.mdx
  pages/docs/index.mdx
Labels: enhancement, size:M, auto-merge

#2130 docs: add compliance FAQs page and supplement other FAQs
  pages/security/_meta.tsx
  pages/security/compliance-faq.mdx
  pages/security/data-regions.mdx
  pages/security/incident-and-breach.mdx
  pages/security/privacy-faq.mdx
  pages/security/security-faq.mdx
Labels: documentation, size:L, auto-merge
