Repository langfuse/langfuse-docs, pull requests merged in 2025-03, with the labels that each got.

#1326 chore: update java spring sample
  pages/docs/integrations/spring-ai.mdx
Labels: documentation, size:M, auto-merge

#1328 feat: add java client changelog post
  pages/changelog/2025-03-03-langfuse-java-client.mdx
  pages/docs/_meta.tsx
  pages/docs/api.mdx
Labels: documentation, size:L, auto-merge

#1329 docs: add blog february update
  pages/blog/2025-02-28-langfuse-february-update.mdx
  public/images/blog/2025-02-28-langfuse-february-update/feature-overview.png
  public/images/blog/2025-02-28-langfuse-february-update/langfuse-february-update.png
  public/images/blog/2025-02-28-langfuse-february-update/llmops-stack.png
  public/images/blog/2025-02-28-langfuse-february-update/otel-integrations.png
Labels: docs, size:M, auto-merge

#1314 docs: tracing environments
  pages/docs/sdk/typescript/guide.mdx
  pages/docs/tracing-features/_meta.tsx
  pages/docs/tracing-features/environments.mdx
Labels: documentation, size:L, auto-merge

#1330 docs: formatting fix
  pages/blog/2024-11-most-used-oss-llmops.mdx
Labels: docs, size:XS, auto-merge

#1331 docs: add llm eval blog post
  pages/blog/2025-03-04-llm-evaluation-101-best-practices-and-challenges.mdx
  public/images/blog/2025-03-04-llm-evaluation/blog-post-example-trace.png
  public/images/blog/2025-03-04-llm-evaluation/blog-post-llm-evaluation.png
  public/images/blog/2025-03-04-llm-evaluation/dataset-example.png
  public/images/blog/2025-03-04-llm-evaluation/eval-score-example.png
  public/images/blog/2025-03-04-llm-evaluation/human-annotation-example.png
  public/images/blog/2025-03-04-llm-evaluation/online-eval-example.png
  public/images/blog/2025-03-04-llm-evaluation/user-feedback.png
Labels: docs, size:L, auto-merge

#1332 docs: edit blog seo title
  pages/blog/2025-03-04-llm-evaluation-101-best-practices-and-challenges.mdx
Labels: docs, size:XS, auto-merge

#1304 Add GAO as Enterprise partner
  pages/enterprise.mdx
Labels: documentation, lgtm, size:XS, auto-merge

#1324 docs: update openllmetry docs
  cookbook/otel_integration_openllmetry.ipynb
  pages/docs/opentelemetry/example-openllmetry.md
  pages/guides/cookbook/otel_integration_openllmetry.md
Labels: docs, size:L, auto-merge

#1333 docs: add xAI / grok cookbook
  .cursor/rules/integration-page.mdc
  cookbook/_routes.json
  cookbook/integration_x_ai_grok.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/xai.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_x_ai_grok.md
  public/images/cookbook/integration-grok/grok-example-trace.png
Labels: docs, size:L, auto-merge

#1334 docs: add cohere integration page
  cookbook/_routes.json
  cookbook/integration_cohere.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/cohere.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_cohere.md
  public/images/cookbook/integration_cohere/cohere-example-trace.png
Labels: docs, size:L, auto-merge

#1335 docs: add fireworks ai integration
  cookbook/_routes.json
  cookbook/integration_fireworks_ai.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/cohere.md
  pages/docs/integrations/other/fireworks-ai.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_fireworks_ai.md
  public/images/cookbook/integration-fireworks-ai/fireworks-ai-example-trace.png
Labels: docs, size:L, auto-merge

#1336 feat: add S3 concurrency control documentation
  pages/self-hosting/configuration.mdx
Labels: documentation, size:XS, auto-merge

#1339 feat: add native environment changelog post
  pages/changelog/2025-03-06-native-environments.mdx
  pages/docs/tracing-features/environments.mdx
Labels: documentation, size:S, auto-merge

#1340 docs: add prompt a/b testing
  pages/docs/prompts/_meta.tsx
  pages/docs/prompts/a-b-testing.mdx
  pages/docs/prompts/get-started.mdx
Labels: docs, size:L, auto-merge

#1341 docs: add Databricks integration
  cookbook/_routes.json
  cookbook/integration_databricks.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/databricks/_meta.tsx
  pages/docs/integrations/databricks/example-python.md
  pages/docs/integrations/databricks/overview.mdx
  pages/docs/integrations/databricks/use-with-playground-and-evals.mdx
  pages/guides/cookbook/integration_databricks.md
  public/images/docs/databricks/add-databricsk-serving-endpoint.png
  public/images/docs/databricks/databricks-add-to-langfuse.png
  public/images/docs/databricks/databricks-evaluations.png
  public/images/docs/databricks/databricks-example-llamaindex-trace.png
  public/images/docs/databricks/databricks-example-trace-langchain.png
  public/images/docs/databricks/databricks-example-trace-openai-sdk.png
  public/images/docs/databricks/databricks-playground.png
  public/images/docs/databricks/databricks-serving-endpoint.png
Labels: documentation, size:XXL, auto-merge

#1337 docs: add novita ai integration
  cookbook/integration_novitaai.ipynb
  cookbook/integration_novitaai.md
  public/images/cookbook/integration-novitaai/novitaai-example-trace.png
Labels: docs, size:L, auto-merge

#1338 Update inkeep widget package
  components/inkeep/InkeepChatButton.tsx
  components/inkeep/InkeepCustomTrigger.tsx
  components/inkeep/InkeepEmbeddedChat.tsx
  components/inkeep/InkeepSearchBar.tsx
  components/inkeep/useInkeepSettings.ts
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:L, auto-merge

#1342 ci: run internal link check
  .github/workflows/ci.yml
  cookbook/integration_cohere.ipynb
  cookbook/integration_databricks.ipynb
  cookbook/integration_litellm_proxy.ipynb
  cookbook/integration_openai_assistants.ipynb
  cookbook/integration_openai_sdk.ipynb
  cookbook/js_integration_litellm_proxy.ipynb
  cookbook/python_decorators.ipynb
  package.json
  pages/blog/langflow.mdx
  pages/changelog/2024-08-08-openai-structured-outputs.mdx
  pages/docs/integrations/databricks/example-python.md
  pages/docs/integrations/litellm/example-proxy-js.md
  pages/docs/integrations/litellm/example-proxy-python.md
  pages/docs/integrations/openai/python/assistants-api.md
  pages/docs/integrations/openai/python/examples.md
  pages/docs/integrations/other/cohere.md
  pages/docs/integrations/other/openrouter.mdx
  pages/docs/opentelemetry/example-openllmetry.md
  pages/docs/opentelemetry/get-started.mdx
  pages/docs/sdk/python/example.md
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/guides/cookbook/integration_cohere.md
  pages/guides/cookbook/integration_databricks.md
  pages/guides/cookbook/integration_litellm_proxy.md
  pages/guides/cookbook/integration_openai_assistants.md
  pages/guides/cookbook/integration_openai_sdk.md
  pages/guides/cookbook/js_integration_litellm_proxy.md
  pages/guides/cookbook/python_decorators.md
  pnpm-lock.yaml
  scripts/check-links.js
Labels: dependencies, size:XXL, auto-merge

#1343 chore: add index pages to videos and cookbook
  components/CookbookIndex.tsx
  components/VideoIndex.tsx
  pages/guides/cookbook/_meta.tsx
  pages/guides/cookbook/index.mdx
  pages/guides/videos/_meta.tsx
  pages/guides/videos/index.mdx
Labels: documentation, size:M, auto-merge

#1344 feat: move /library into main docs menu
  components/FooterMenu.tsx
  components/MenuSwitcher.tsx
  pages/_meta.tsx
  pages/library/_meta.tsx
  pages/library/index.mdx
  src/overrides.css
Labels: documentation, size:M, auto-merge

#1346 docs: hf course images
  public/images/cookbook/huggingface-agent-course/first-example-trace.png
  public/images/cookbook/huggingface-agent-course/langfuse-dashboard.png
  public/images/cookbook/huggingface-agent-course/smolagents-attributes.png
  public/images/cookbook/huggingface-agent-course/smolagents-costs.png
  public/images/cookbook/huggingface-agent-course/smolagents-latency.png
Labels: docs, size:XS, auto-merge

#1347 docs: add image and fix typo
  cookbook/_routes.json
  cookbook/integration_groq_sdk.ipynb
  public/images/cookbook/huggingface-agent-course/trace-tree.png
Labels: docs, size:XS, auto-merge

#1348 Add novita ai guide
  cookbook/_routes.json
  cookbook/integration_novitaai.ipynb
  cookbook/integration_togetherai.ipynb
  cookbook/integration_x_ai_grok.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/novitaai.md
  pages/docs/integrations/other/togetherai.md
  pages/docs/integrations/other/xai.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_groq_sdk.md
  pages/guides/cookbook/integration_novitaai.md
  pages/guides/cookbook/integration_togetherai.md
  pages/guides/cookbook/integration_x_ai_grok.md
Labels: documentation, size:XL, auto-merge

#1350 docs: edit images for hf
  public/images/cookbook/huggingface-agent-course/dataset-run-comparison.png
  public/images/cookbook/huggingface-agent-course/dataset_runs.png
  public/images/cookbook/huggingface-agent-course/evaluator-template.png
  public/images/cookbook/huggingface-agent-course/evaluator.png
  public/images/cookbook/huggingface-agent-course/first-example-trace.png
  public/images/cookbook/huggingface-agent-course/langfuse-dashboard.png
  public/images/cookbook/huggingface-agent-course/llm-as-a-judge-score.png
  public/images/cookbook/huggingface-agent-course/smolagents-attributes.png
  public/images/cookbook/huggingface-agent-course/smolagents-costs.png
  public/images/cookbook/huggingface-agent-course/smolagents-latency.png
  public/images/cookbook/huggingface-agent-course/trace-tree.png
  public/images/cookbook/huggingface-agent-course/user-feedback-gradio.png
Labels: docs, size:XS, auto-merge

#1351 docs: add community hour banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1354 docs: update Otel docs
  cookbook/integration_autogen.ipynb
  cookbook/integration_semantic_kernel.ipynb
  cookbook/integration_smolagents.ipynb
  cookbook/otel_integration_openlit.ipynb
  cookbook/otel_integration_python_sdk.ipynb
  pages/docs/integrations/autogen.md
  pages/docs/integrations/semantic-kernel.md
  pages/docs/integrations/smolagents.md
  pages/docs/opentelemetry/example-openlit.md
  pages/docs/opentelemetry/example-python-sdk.md
  pages/guides/cookbook/integration_autogen.md
  pages/guides/cookbook/integration_grpq_sdk.md
  pages/guides/cookbook/integration_semantic_kernel.md
  pages/guides/cookbook/integration_smolagents.md
  pages/guides/cookbook/otel_integration_openlit.md
  pages/guides/cookbook/otel_integration_python_sdk.md
Labels: documentation, size:XXL, auto-merge

#1302 docs: add Quarkus LangChain4j integration
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/quarkus-langchain4j.mdx
Labels: docs, size:L

#1359 docs: fix pydantic ai docs
  cookbook/integration_pydantic_ai.ipynb
  pages/docs/integrations/pydantic-ai.md
  pages/guides/cookbook/integration_pydantic_ai.md
  public/images/cookbook/otel-integration-pydantic-ai/pydanticai-openai-trace-tree.png
Labels: docs, size:L, auto-merge

#1358 docs: nits
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/openai-agents.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_openai-agents.md
Labels: docs, size:M, auto-merge

#1360 docs: prompt composability
  pages/changelog/2025-03-12-prompt-composability.mdx
  pages/docs/prompts/get-started.mdx
Labels: size:M

#1361 chore: add security thoughts for docker compose hosting
  pages/self-hosting/docker-compose.mdx
  pages/self-hosting/local.mdx
Labels: documentation, size:S, auto-merge

#1363 docs(auth): add AUTH_GITLAB_URL to Gitlab SSO doc
  pages/self-hosting/authentication-and-sso.mdx
Labels: docs, size:XS, auto-merge

#1365 docs: edit opena ai agents cookbook
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/openai-agents.md
  pages/guides/cookbook/integration_openai-agents.md
  public/images/cookbook/integration_openai-agents/openai-agent-sdk-custom-attributes.png
Labels: docs, size:L, auto-merge

#1368 docs: edit title for open ai agents guide
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/openai-agents.md
  pages/guides/cookbook/integration_openai-agents.md
Labels: docs, size:S, auto-merge

#1369 docs: edit video for openai agents
  cookbook/example_evaluating_crew-ai_agents.md
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/openai-agents.md
Labels: documentation, size:L, auto-merge

#1370 docs: add example on evaluating OpenAI agents SDK
  cookbook/_routes.json
  cookbook/example_evaluating_crew-ai_agents.md
  cookbook/example_evaluating_openai_agents.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/openai/python/_meta.tsx
  pages/docs/integrations/openaiagentssdk/_meta.tsx
  pages/docs/integrations/openaiagentssdk/example-evaluating-openai-agents.md
  pages/docs/integrations/openaiagentssdk/openai-agents.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/example_evaluating_openai_agents.md
  pages/guides/cookbook/integration_openai-agents.md
  public/images/cookbook/integration_openai-agents/dashboard-dark.png
  public/images/cookbook/integration_openai-agents/dataset-run-comparison.png
  public/images/cookbook/integration_openai-agents/dataset_runs.png
  public/images/cookbook/integration_openai-agents/evaluator-template.png
  public/images/cookbook/integration_openai-agents/evaluator.png
  public/images/cookbook/integration_openai-agents/example-dataset.png
  public/images/cookbook/integration_openai-agents/first-example-trace.png
  public/images/cookbook/integration_openai-agents/gpt-4o-costs.png
  public/images/cookbook/integration_openai-agents/llm-as-a-judge-score.png
  public/images/cookbook/integration_openai-agents/open-ai-agent-user-feedback.png
  public/images/cookbook/integration_openai-agents/openai-agent-latency.png
  public/images/cookbook/integration_openai-agents/openai-agent-sdk-custom-attributes.png
  public/images/cookbook/integration_openai-agents/trace-tree.png
Labels: docs, size:XXL, auto-merge

#1371 chore: update auth method env naming
  pages/self-hosting/authentication-and-sso.mdx
Labels: documentation, size:XS, auto-merge

#1372 docs: add images for HF course
  public/images/cookbook/huggingface-agent-course/langgraph-trace-legit.png
  public/images/cookbook/huggingface-agent-course/langgraph-trace-spam.png
Labels: docs, size:XS, auto-merge

#1373 docs(changelog): openai response API
  pages/changelog/2025-03-17-openai-response-api-support.mdx
Labels: docs, size:M

#1374 docs: add link to oai agents overview
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/openaiagentssdk/openai-agents.md
  pages/guides/cookbook/integration_openai-agents.md
Labels: docs, size:S, auto-merge

#1375 docs: add redirect
  next.config.mjs
Labels: docs, size:XS

#1376 docs: evironment faq update
  pages/faq/all/managing-different-environments.mdx
Labels: docs, size:S, auto-merge

#1377 chore: add new batch export external endpoint to docs
  pages/self-hosting/configuration.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:M, auto-merge

#1264 chore: update pricing structure to add new core plan and teams add-on
  components/availability.tsx
  components/home/Pricing.tsx
  components/ui/hover-card.tsx
  components/ui/tooltip.tsx
  package.json
  pages/docs/analytics/posthog.mdx
  pages/docs/data-deletion.mdx
  pages/docs/data-retention.mdx
  pages/docs/datasets/prompt-experiments.mdx
  pages/docs/opentelemetry/get-started.mdx
  pages/docs/playground.mdx
  pages/docs/rbac.mdx
  pages/docs/scores/annotation.mdx
  pages/docs/scores/custom.mdx
  pages/docs/scores/model-based-evals.mdx
  pages/faq/all/api-limits.mdx
  pnpm-lock.yaml
Labels: size:XL

#1325 changelog: trace and prompt screen
  pages/changelog/2025-03-19-new-prompt-view.mdx
  pages/changelog/2025-03-19-new-trace-view.mdx
Labels: documentation, size:M, auto-merge

#1382 docs: fix grammar for clarity in self-hosting section
  pages/faq/all/langsmith-alternative.mdx
Labels: docs, size:XS

#1381 docs: page improvements
  pages/blog/2024-07-ai-agent-observability-with-langfuse.mdx
  pages/docs/scores/model-based-evals.mdx
  public/images/docs/eval-config.png
  public/images/docs/eval-score.png
  public/images/docs/evals-log.png
  public/images/docs/llm-as-a-judge/add-llm.png
  public/images/docs/llm-as-a-judge/eval-config.png
  public/images/docs/llm-as-a-judge/eval-score.png
  public/images/docs/llm-as-a-judge/evals-log.png
  public/images/docs/llm-as-a-judge/evaluator-template.png
Labels: docs, size:M, auto-merge

#1383 docs: Mlflow integration page
  cookbook/_routes.json
  cookbook/otel_integration_mlflow.ipynb
  cookbook/otel_integration_openlit.ipynb
  pages/docs/opentelemetry/_meta.tsx
  pages/docs/opentelemetry/example-mlflow.md
  pages/docs/opentelemetry/example-openlit.md
  pages/docs/opentelemetry/get-started.mdx
  pages/guides/cookbook/otel_integration_mlflow.md
  pages/guides/cookbook/otel_integration_openlit.md
  public/images/cookbook/otel-integration-mlflow/mlflow-openai-trace.png
Labels: documentation, size:XL, auto-merge

#1386 docs: add agent graph docs
  pages/changelog/2025-02-14-trace-graph-view.mdx
  pages/docs/tracing-features/agent-graphs.mdx
  pages/docs/tracing.mdx
Labels: documentation, size:M, auto-merge

#1387 docs(changelog): traces table preview
  pages/changelog/2025-03-21-table-peek-view.mdx
Labels: docs, size:M, auto-merge

#1388 docs: add link to llm-as-a-judge page
  pages/docs/scores/model-based-evals.mdx
Labels: documentation, size:XS, auto-merge

#1390 feat: document new langfuse.metadata behaviour
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:S, auto-merge

#1392 docs: add cookbook on evaluating Langgraph agents
  cookbook/_routes.json
  cookbook/example_langgraph_agents.ipynb
  pages/docs/integrations/langchain/_meta.tsx
  pages/docs/integrations/langchain/example-langgraph-agents.md
  pages/guides/cookbook/example_langgraph_agents.md
  public/images/cookbook/example-langgraph-evaluation/agent-latency.png
  public/images/cookbook/example-langgraph-evaluation/custom-attributes.png
  public/images/cookbook/example-langgraph-evaluation/dataset-run-comparison.png
  public/images/cookbook/example-langgraph-evaluation/dataset_runs.png
  public/images/cookbook/example-langgraph-evaluation/example-dataset.png
  public/images/cookbook/example-langgraph-evaluation/first-example-trace.png
  public/images/cookbook/example-langgraph-evaluation/gpt-4o-costs.png
  public/images/cookbook/example-langgraph-evaluation/llm-as-a-judge-score.png
  public/images/cookbook/example-langgraph-evaluation/trace-tree.png
  public/images/cookbook/example-langgraph-evaluation/user-feedback.png
Labels: documentation, size:XXL, auto-merge

#1393 chore: remove experimental warning from azure blob storage
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:XS, auto-merge

#1394 feat: add blob storage integration docs
  pages/docs/query-traces.mdx
  public/images/docs/blob-storage-integration.png
Labels: documentation, size:S, auto-merge

#1395 docs: add community hour banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1396 chore: add guidance on export format for s3 integration
  pages/docs/query-traces.mdx
Labels: docs, size:XS, auto-merge

#1397 chore: clarify what langfuse.metadata for otel accepts
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:S, auto-merge

#1391 docs(quarkus): langchain4j tracing configuration with otel
  pages/docs/integrations/quarkus-langchain4j.mdx
Labels: docs, lgtm, size:S

#1399 chore: add deletion disclaimer for GCS
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:XS, auto-merge

#1400 docs: remove community hour banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1402 docs: fix crewai openlit instrumentation
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: docs, size:S, auto-merge

#1398 chore: add scaling guide for self-hosted deployments
  pages/self-hosting/_meta.tsx
  pages/self-hosting/infrastructure/clickhouse.mdx
  pages/self-hosting/scaling.mdx
  pages/self-hosting/troubleshooting.mdx
Labels: documentation, size:M, auto-merge

#1404 chore: minor clarifications
  pages/docs/data-deletion.mdx
  public/images/docs/blob-storage-integration.png
Labels: documentation, size:XS, auto-merge

#1405 docs: new recordings
  components-mdx/prompt-overview-gifs.mdx
  components-mdx/tracing-overview-gifs.mdx
Labels: documentation, size:M, auto-merge

#1401 [docs] Add integration with Mastra
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/mastra.mdx
  public/images/docs/langfuse-mastra-trace.png
Labels: docs, size:L

#1406 feat: document native GCS support
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:M, auto-merge
