Repository langfuse/langfuse-docs, pull requests merged in 2025-05, with the labels that each got.

#1472 feat: new /security
  components-mdx/self-host-help-footer.mdx
  components/FooterMenu.tsx
  components/home/Pricing.tsx
  components/home/Security.tsx
  next.config.mjs
  pages/_meta.tsx
  pages/changelog/2024-04-10-ISO-27001-certification.mdx
  pages/changelog/2024-04-30-SOC-2-Type-2-certification.mdx
  pages/docs/_meta.tsx
  pages/docs/data-security-privacy.mdx
  pages/docs/tracing-features/masking.mdx
  pages/enterprise.mdx
  pages/faq/all/cloud-data-regions.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
  pages/faq/all/inviting-in-langfuse.mdx
  pages/faq/all/ten-reasons-to-use-langfuse.mdx
  pages/faq/all/where-is-my-project.mdx
  pages/security/_meta.tsx
  pages/security/data-regions.mdx
  pages/security/dependencies.mdx
  pages/security/encryption.mdx
  pages/security/gdpr.mdx
  pages/security/hipaa.mdx
  pages/security/index.mdx
  pages/security/iso27001.mdx
  pages/security/penetration-testing.mdx
  pages/security/responsible-disclosure.mdx
  pages/security/soc2.mdx
  pages/security/whistleblowing.mdx
  pages/self-hosting/encryption.mdx
  pages/self-hosting/index.mdx
  pages/self-hosting/upgrade-guides/upgrade-v1-to-v2.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
  pages/self-hosting/upgrade.mdx
  pages/self-hosting/v2/deployment-guide.mdx
  src/overrides.css
Labels: documentation, size:XL, auto-merge

#1473 chore: move /docs/open-source to /open-source
  components/FooterMenu.tsx
  next.config.mjs
  pages/_meta.tsx
  pages/changelog/2024-08-14-ui-customization.mdx
  pages/docs/_meta.tsx
  pages/docs/fine-tuning.mdx
  pages/docs/index.mdx
  pages/docs/query-traces.mdx
  pages/docs/roadmap.mdx
  pages/enterprise.mdx
  pages/faq/all/ten-reasons-to-use-langfuse.mdx
  pages/open-source.mdx
  pages/oss-friends.mdx
  pages/self-hosting/license-key.mdx
  pages/why.mdx
Labels: documentation, size:M, auto-merge

#1474 feat: improve security privacy docs
  pages/security/_meta.tsx
  pages/security/auth.mdx
  pages/security/data-regions.mdx
  pages/security/dpa.mdx
  pages/security/gdpr.mdx
  pages/security/hipaa.mdx
  pages/security/incident-and-breach.mdx
  pages/security/index.mdx
  pages/security/manage-personal-data.mdx
  pages/security/policies.mdx
  pages/security/privacy-faq.mdx
  pages/security/subprocessors.mdx
  pages/security/vulnerability-management.mdx
  public/images/security/sso-signin.png
  src/overrides.css
Labels: documentation, size:L, auto-merge

#1475 ci: check that md and mdx docs have at most one h1
  .github/workflows/ci.yml
  pages/faq/all/ai-research-assistant-monitoring.mdx
  scripts/check-h1-headings.js
Labels: documentation, size:L

#1476 docs: add hyperscaler templates
  next.config.mjs
  pages/self-hosting/_meta.tsx
  pages/self-hosting/aws.mdx
  pages/self-hosting/azure.mdx
  pages/self-hosting/docker-compose.mdx
  pages/self-hosting/docker.mdx
  pages/self-hosting/gcp.mdx
  pages/self-hosting/index.mdx
  pages/self-hosting/infrastructure/containers.mdx
  pages/self-hosting/kubernetes-helm.mdx
  pages/self-hosting/local.mdx
Labels: docs, size:XL, auto-merge

#1477 docs: update self-host feature list
  components-mdx/self-host-features.mdx
Labels: documentation, size:M, auto-merge

#1478 chore: clarify media and batch export S3 credential usage
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: docs, size:XS, auto-merge

#1479 docs: add note to openai agents sdk docs
  cookbook/example_evaluating_openai_agents.ipynb
  pages/docs/integrations/langchain/example-python.md
  pages/docs/integrations/openaiagentssdk/example-evaluating-openai-agents.md
  pages/docs/integrations/openaiagentssdk/openai-agents.md
  pages/guides/cookbook/example_evaluating_openai_agents.md
  pages/guides/cookbook/integration_langchain.md
  pages/guides/cookbook/integration_openai-agents.md
Labels: documentation, size:S, auto-merge

#1480 docs: add configurable dashboards to blog update
  pages/blog/2025-04-30-langfuse-april-update.mdx
  public/images/blog/2025-04-30-langfuse-april-update/configurable-dashboards.png
Labels: docs, size:S, auto-merge

#1481 [docs] Add integration with VoltAgent
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/voltagent.mdx
  public/images/docs/langfuse-voltagent-trace.png
Labels: docs, size:L

#1485 chore: add springer nature logo
  components/home/Usage.tsx
  components/home/img/springernature_dark.svg
  components/home/img/springernature_light.svg
Labels: documentation, size:S, auto-merge

#1484 docs: reference cloud sso docs in self-hosting docs
  pages/security/auth.mdx
  pages/self-hosting/authentication-and-sso.mdx
Labels: documentation, size:XS, auto-merge

#1487 feat: add details on userId and sessionId tracking on SpringAi spans
  pages/docs/integrations/spring-ai.mdx
Labels: documentation, size:M, auto-merge

#1482 docs: add banner re sf event
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1492 docs: add Minimum Infrastructure Requirements to scaling doc
  pages/self-hosting/_meta.tsx
  pages/self-hosting/scaling.mdx
Labels: documentation, size:S, auto-merge

#1496 docs: add data migration notebook
  cookbook/_routes.json
  cookbook/example_data_migration.ipynb
  pages/guides/cookbook/example_data_migration.md
Labels: size:XXL, auto-merge

#1497 docs: add run-level-scores changelog
  pages/changelog/2025-05-07-run-level-scores.mdx
Labels: docs, size:M, auto-merge

#1498 docs: edit bedrock agents cookbook
  cookbook/_routes.json
  cookbook/example_bedrock_agents.ipynb
  pages/docs/integrations/bedrock/example-bedrock-agents.md
  pages/docs/integrations/bedrock/example-bedrock-agents.mdx
Labels: documentation, size:XL, auto-merge

#1499 docs: clean up categories in guide section
  cookbook/_routes.json
  cookbook/integration_amazon_bedrock.md
  cookbook/integration_autogen.ipynb
  cookbook/integration_cohere.ipynb
  cookbook/integration_crewai.ipynb
  cookbook/integration_databricks.ipynb
  cookbook/integration_deepseek_openai_sdk.ipynb
  cookbook/integration_dspy.ipynb
  cookbook/integration_firecrawl.ipynb
  cookbook/integration_fireworks_ai.ipynb
  cookbook/integration_google_adk.ipynb
  cookbook/integration_huggingface_openai_sdk.ipynb
  cookbook/integration_llamaindex_workflows.ipynb
  cookbook/integration_mistral_sdk.ipynb
  cookbook/integration_novitaai.ipynb
  cookbook/integration_smolagents.ipynb
  cookbook/integration_togetherai.ipynb
  cookbook/integration_x_ai_grok.ipynb
  cookbook/js_integration_llamaindex.ipynb
  cookbook/js_langfuse_sdk.ipynb
  cookbook/langfuse_sdk_performance_test.ipynb
  cookbook/otel_integration_arize.ipynb
  cookbook/otel_integration_python_sdk.ipynb
  cookbook/prompt_management_langchain.ipynb
  pages/docs/integrations/autogen.md
  pages/docs/integrations/bedrock/example-bedrock-agents.md
  pages/docs/integrations/crewai.md
  pages/docs/integrations/databricks/example-python.md
  pages/docs/integrations/google-adk.md
  pages/docs/integrations/llama-index/example-js-llamaindex.md
  pages/docs/integrations/mistral-sdk.md
  pages/docs/integrations/other/cohere.md
  pages/docs/integrations/other/firecrawl.md
  pages/docs/integrations/other/fireworks-ai.md
  pages/docs/integrations/other/novitaai.md
  pages/docs/integrations/other/togetherai.md
  pages/docs/integrations/other/xai.md
  pages/docs/integrations/smolagents.md
  pages/docs/opentelemetry/example-arize.md
  pages/docs/opentelemetry/example-python-sdk.md
  pages/docs/sdk/typescript/example-notebook.md
  pages/guides/cookbook/integration_autogen.md
  pages/guides/cookbook/integration_cohere.md
  pages/guides/cookbook/integration_crewai.md
  pages/guides/cookbook/integration_databricks.md
  pages/guides/cookbook/integration_firecrawl.md
  pages/guides/cookbook/integration_fireworks_ai.md
  pages/guides/cookbook/integration_google_adk.md
  pages/guides/cookbook/integration_mistral_sdk.md
  pages/guides/cookbook/integration_novitaai.md
  pages/guides/cookbook/integration_smolagents.md
  pages/guides/cookbook/integration_togetherai.md
  pages/guides/cookbook/integration_x_ai_grok.md
  pages/guides/cookbook/js_integration_llamaindex.md
  pages/guides/cookbook/js_langfuse_sdk.md
  pages/guides/cookbook/langfuse_sdk_performance_test.md
  pages/guides/cookbook/otel_integration_arize.md
  pages/guides/cookbook/otel_integration_python_sdk.md
Labels: documentation, size:M, auto-merge

#1502 chore: ft search changelog
  pages/changelog/2025-05-09-full-text-search.mdx
  public/images/changelog/2025-05-09-ft-search.mp4
Labels: documentation, size:S, auto-merge

#1504 Ragflow integration
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/ragflow.mdx
  public/images/docs/ragflow/ragflow-configuration.gif
  public/images/docs/ragflow/ragflow-example-trace.png
Labels: documentation, size:M, auto-merge

#1507 docs: add links to free trial key
  pages/faq/all/self-hosting-langfuse.mdx
  pages/self-hosting/index.mdx
  pages/self-hosting/organization-creators.mdx
  pages/self-hosting/ui-customization.mdx
Labels: docs, size:XS, auto-merge

#1508 chore: /talk-to-us instead of /schedule-demo
  components-mdx/self-host-help-footer.mdx
  components/FooterMenu.tsx
  components/MainContentWrapper.tsx
  components/WatchDemoPage.tsx
  components/home/Pricing.tsx
  next.config.mjs
  pages/enterprise.mdx
  pages/self-hosting/index.mdx
  pages/self-hosting/upgrade-guides/upgrade-v1-to-v2.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
  pages/self-hosting/upgrade.mdx
  pages/self-hosting/v2/deployment-guide.mdx
  pages/support.mdx
  pages/talk-to-us.mdx
Labels: documentation, size:M, auto-merge

#1512 feat: document public metrics api
  pages/changelog/2025-05-12-custom-metrics-api.mdx
  pages/docs/analytics/metrics-api.mdx
Labels: documentation, size:L, auto-merge

#1516 fix: adjust batch export env variable
  pages/self-hosting/configuration.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:XS, auto-merge

#1517 docs: add run level scores
  pages/docs/scores/data-model.mdx
  pages/docs/tracing-data-model.mdx
Labels: docs, size:S, auto-merge

#1518 Update tracing-overview-gifs.mdx
  components-mdx/tracing-overview-gifs.mdx
Labels: size:XS

#1519 docs: remove banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1522 docs: datasets rate limit group
  components/home/Pricing.tsx
  pages/faq/all/api-limits.mdx
Labels: docs, size:S, auto-merge

#1523 chore: add postgres note to scaling doc
  pages/self-hosting/scaling.mdx
Labels: documentation, size:XS, auto-merge

#1527 docs: add launch week 3 announcement
  next.config.mjs
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/docs/integrations/bedrock/example-bedrock-agents.md
  public/images/blog/2025-05-19-launch-week-3/lw3-community-hour.png
  public/images/blog/2025-05-19-launch-week-3/lw3-product-hunt.png
  public/images/blog/2025-05-19-launch-week-3/lw3-teaser-blog.png
Labels: docs, size:L, auto-merge

#1528 docs: LANGFUSE_UI_VISIBLE_PRODUCT_MODULES and LANGFUSE_UI_HIDDEN_PRODUCT_MODULES
  .cursor/rules/changelog-posts.mdc
  pages/changelog/2025-05-15-product-module-visibility.mdx
  pages/self-hosting/ui-customization.mdx
Labels: documentation, size:M, auto-merge

#1532 docs: update lauch week
  pages/blog/2025-05-19-launch-week-3.mdx
  theme.config.tsx
Labels: documentation, size:M, auto-merge

#1535 Fix Academy module text errors
  components/InteractiveQuiz.tsx
  pages/academy/02-tracing.mdx
Labels: size:S, codex

#1536 docs: add strands agents notebook
  cookbook/_routes.json
  cookbook/integration_aws_strands_agents.ipynb
  cookbook/interation_aws_strands_agents.md
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/strands-agents.md
  pages/guides/cookbook/integration_aws_strands_agents.md
  public/images/cookbook/integration_aws_strands_agents/strands-agents-trace.png
Labels: documentation, size:XL, auto-merge

#1539 Fix LangFuse casing
  pages/docs/analytics/posthog.mdx
  pages/docs/integrations/quarkus-langchain4j.mdx
  pages/guides/videos/beginners-guide-to-rag-evaluation.mdx
  pages/jp.mdx
Labels: documentation, size:S, auto-merge, codex

#1540 docs: update AGENTS guidelines
  AGENTS.md
Labels: documentation, size:S, codex

#1544 Update enterprise page for OSS support
  pages/enterprise.mdx
Labels: size:XS, codex

#1537 Fix docs h1 title casing
  pages/docs/fine-tuning.mdx
  pages/docs/integrations/dify.mdx
  pages/docs/integrations/llama-index/deprecated-llama-index-callback.mdx
  pages/docs/integrations/mastra.mdx
  pages/docs/integrations/mirascope/tracing.mdx
  pages/docs/integrations/openai/python/track-errors.mdx
  pages/docs/integrations/other/ragas.mdx
  pages/docs/rbac.mdx
  pages/docs/scores/model-based-evals.mdx
  pages/docs/sdk/python/decorators.mdx
  pages/docs/tracing-features/masking.mdx
  pages/docs/tracing-features/tags.mdx
  scripts/fix_titlecase.py
Labels: documentation, size:M, auto-merge, codex

#1541 chore: Fix GitHub capitalization in docs
  .cursor/rules/available-internal-links.mdc
  components-mdx/github-cta.mdx
  pages/blog/2024-11-17-launch-week-2.mdx
  pages/blog/2025-04-24-how-we-use-llms-to-scale-langfuse.mdx
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/blog/langchain-integration.mdx
  pages/blog/launch-week-1.mdx
  pages/changelog/2025-01-23-LLM-calls-extra-headers.mdx
  pages/changelog/2025-02-14-trace-graph-view.mdx
  pages/docs/integrations/openwebui.mdx
  pages/docs/sdk/overview.mdx
  pages/docs/sdk/typescript/guide-web.mdx
  pages/docs/sdk/typescript/guide.mdx
  pages/faq/all/best-helicone-alternative.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/faq/all/langfuse-support.mdx
  pages/faq/all/llm-analytics-101.mdx
  pages/faq/all/report-feedback-bug.mdx
  pages/jp.mdx
  pages/privacy.mdx
Labels: documentation, size:M, auto-merge, codex

#1546 chore: support chat hides thread references
  components/supportChat/index.tsx
Labels: enhancement, size:XS, auto-merge, codex

#1550 docs: add trubrics integration doc
  .cursor/rules/available-internal-links.mdc
  components/home/Pricing.tsx
  next.config.mjs
  pages/blog/launch-week-1.mdx
  pages/changelog/2024-04-22-posthog-integration.mdx
  pages/changelog/2024-12-20-posthog-integration-GA.mdx
  pages/docs/analytics/_meta.tsx
  pages/docs/analytics/integrations/_meta.tsx
  pages/docs/analytics/integrations/posthog.mdx
  pages/docs/analytics/integrations/trubrics.mdx
  pages/faq/all/chatbot-analytics.mdx
  pages/guides/cookbook/integration_llama_index_posthog_mistral.md
  pages/guides/videos/posthog-integration.mdx
  pages/self-hosting/license-key.mdx
Labels: docs, size:L, auto-merge

#1551 docs: Add Coval integration
  pages/docs/analytics/integrations/_meta.tsx
  pages/docs/analytics/integrations/coval.mdx
Labels: documentation, size:M, auto-merge, codex

#1552 docs: update naming of strands agents
  cookbook/integration_aws_strands_agents.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/strands-agents.md
  pages/guides/cookbook/integration_aws_strands_agents.md
Labels: documentation, size:S, auto-merge

#1553 chore: make a small fix to get started
  pages/docs/index.mdx
Labels: documentation, size:XS, auto-merge

#1545 launch week day 1
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-09-full-text-search.mdx
  pages/changelog/2025-05-19-full-text-search.mdx
  public/images/changelog/2025-05-09-ft-search.mp4
  theme.config.tsx
Labels: documentation, size:L, auto-merge

#1554 docs: langfuse launch week 3 day 2
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-20-save-table-views.mdx
  theme.config.tsx
Labels: documentation, size:M

#1555 docs: update crewai, mlflow instead of openlit
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: docs, size:M, auto-merge

#1559 docs: update changelog lw3-2
  pages/changelog/2025-05-20-save-table-views.mdx
Labels: docs, size:S, auto-merge

#1564 feat: create custom dashboard changelog
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-21-custom-dashboards.mdx
  public/images/changelog/2025-05-21-custom-dashboards/curated-dashboard.png
  public/images/changelog/2025-05-21-custom-dashboards/custom-dashboard.png
  public/images/changelog/2025-05-21-custom-dashboards/widget-creator.png
Labels: enhancement, size:M, auto-merge

#1562 docs: update banner + /ph redirect
  next.config.mjs
  theme.config.tsx
Labels: docs, size:S

#1565 docs: update video
  pages/blog/2025-05-19-launch-week-3.mdx
Labels: documentation, size:XS, auto-merge

#1567 chore: add networking docs
  pages/security/_meta.tsx
  pages/security/networking.mdx
Labels: documentation, size:S

#1566 chore: update rate-limits for metrics-api, deprecate daily metrics
  .cursor/rules/available-internal-links.mdc
  components/home/Pricing.tsx
  next.config.mjs
  pages/changelog/2024-02-19-metrics-api-endpoint.mdx
  pages/docs/analytics/_meta.tsx
  pages/docs/analytics/daily-metrics-api.mdx
  pages/docs/analytics/metrics-api.mdx
  pages/docs/roadmap.mdx
  pages/faq/all/api-limits.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
Labels: documentation, size:L, auto-merge

#1568 chore: update data retention to have a minimum of 3 days
  pages/changelog/2025-01-30-data-retention.mdx
  pages/docs/data-retention.mdx
  pages/security/privacy-faq.mdx
Labels: documentation, size:XS, auto-merge

#1569 feat: terraform modules changelog
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-22-terraform-modules.mdx
  public/images/changelog/2025-05-22-hyperscaler-terraform-modules/hyperscaler-templates.png
  theme.config.tsx
Labels: documentation, enhancement, size:L, auto-merge

#1570 chore: add AWS S3 KMS setups
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:M, auto-merge

#1557 Documentation Update: DSPY
  pages/docs/integrations/dspy.md
Labels: documentation, lgtm, size:L

#1573 chore: dynamically load terraform readme for latest changelog to make this more maintainable
  pages/changelog/2025-05-22-terraform-modules.mdx
Labels: size:L, auto-merge

#1574 changelog: add claude 4 support
  pages/changelog/2025-05-22-claude-4-support.mdx
Labels: documentation, size:S

#1575 docs: clarify sso via oidc
  pages/security/auth.mdx
Labels: docs, size:XS, auto-merge

#1576 chore: add telus logo
  components/home/Usage.tsx
  components/home/img/telus_dark.png
  components/home/img/telus_light.png
Labels: size:S, auto-merge

#1577 chore: add s3 concurrency section
  pages/self-hosting/scaling.mdx
Labels: documentation, size:S, auto-merge

#1560 add python v3 docs page
  cookbook/python_decorators.ipynb
  cookbook/python_sdk_low_level.ipynb
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-23-otel-based-python-sdk.mdx
  pages/docs/get-started.mdx
  pages/docs/sdk/python/_meta.tsx
  pages/docs/sdk/python/decorators.mdx
  pages/docs/sdk/python/example.md
  pages/docs/sdk/python/low-level-sdk.md
  pages/docs/sdk/python/sdk-v3.mdx
  pages/docs/tracing-features/environments.mdx
  pages/docs/tracing-features/log-levels.mdx
  pages/docs/tracing-features/masking.mdx
  pages/docs/tracing-features/metadata.mdx
  pages/docs/tracing-features/multi-modality.mdx
  pages/docs/tracing-features/releases-and-versioning.mdx
  pages/docs/tracing-features/sampling.mdx
  pages/docs/tracing-features/sessions.mdx
  pages/docs/tracing-features/tags.mdx
  pages/docs/tracing-features/trace-ids.mdx
  pages/docs/tracing-features/url.mdx
  pages/docs/tracing-features/users.mdx
  pages/docs/tracing.mdx
  pages/guides/cookbook/python_decorators.md
  pages/guides/cookbook/python_sdk_low_level.md
  theme.config.tsx
Labels: documentation, size:XXL

#1579 docs: change changelog image
  pages/changelog/2025-05-23-otel-based-python-sdk.mdx
  public/images/changelog/2025-05-23-otel-based-python-sdk.png
Labels: docs, size:XS, auto-merge

#1580 docs: LW3-6 Langfuse Eval Library
  pages/blog/2025-05-19-launch-week-3.mdx
  pages/changelog/2025-05-24-langfuse-evaluator-library.mdx
  public/images/changelog/2025-05-24-langfuse-evaluator-library.png
  public/images/changelog/2025-05-24-langfuse-evaluator-library/default-eval-model.png
  public/images/changelog/2025-05-24-langfuse-evaluator-library/eval-library.png
  public/images/changelog/2025-05-24-langfuse-evaluator-library/trace-examples.png
  theme.config.tsx
Labels: documentation, size:L

#1582 chore: add to handling failed migration docs
  pages/self-hosting/troubleshooting.mdx
Labels: documentation, size:XS, auto-merge

#1584 docs: add agno agents
  cookbook/_routes.json
  cookbook/integration_agno_agents.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/agno-agents.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_agno_agents.md
  public/images/cookbook/integration-agno-agents/agno-agents-openinference.png
  public/images/cookbook/integration-agno-agents/agno-agents-openlit.png
Labels: docs, size:XL, auto-merge

#1587 docs: add eval library documentation
  pages/docs/scores/model-based-evals.mdx
  public/images/docs/evaluator-mapping.png
  public/images/docs/evaluator-overview.png
  public/images/docs/evaluator-trace-filter.png
Labels: documentation, size:L, auto-merge

#1549 docs: add pipecat integration
  pages/changelog/2025-05-29-pipecat-integration.mdx
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/pipecat.mdx
Labels: documentation, size:L, auto-merge, codex

#1591 chore: add incorrect query troubleshooting for clickhouse on azure
  pages/self-hosting/infrastructure/clickhouse.mdx
Labels: documentation, size:XS, auto-merge

#1592 Add Voice AI library section
  pages/library/index.mdx
Labels: docs, size:XS, auto-merge, codex
