Repository langfuse/langfuse-docs, pull requests merged in 2025-02, with the labels that each got.

#1227 chore: add o1 prompting post to library
  pages/library.mdx
Labels: documentation, size:XS, auto-merge

#1213 feat: add opentelemetry preview documentation
  cookbook/_routes.json
  cookbook/otel_integration_openlit.ipynb
  cookbook/otel_integration_openllmetry.ipynb
  cookbook/otel_integration_pydantic_ai.ipynb
  next.config.mjs
  pages/docs/_meta.tsx
  pages/docs/opentelemetry/_meta.tsx
  pages/docs/opentelemetry/example-openlit.md
  pages/docs/opentelemetry/example-openllmetry.md
  pages/docs/opentelemetry/example-opentelemetry-collector.mdx
  pages/docs/opentelemetry/example-pydantic-ai.md
  pages/docs/opentelemetry/get-started.mdx
  pages/guides/cookbook/otel_integration_openlit.md
  pages/guides/cookbook/otel_integration_openllmetry.md
  pages/guides/cookbook/otel_integration_pydantic_ai.md
  pages/guides/cookbook/otel_integration_traceloop.md
  public/images/cookbook/otel-integration-openlit/openlit-openai-trace.png
  public/images/cookbook/otel-integration-openllmetry/openllmetry-openai-trace.png
  public/images/cookbook/otel-integration-pydantic-ai/pydanticai-openai-trace-tree.png
Labels: documentation, size:XXL, auto-merge

#1228 chore: remove note on strict otel ratelimits
  pages/docs/opentelemetry/example-openllmetry.md
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:XS, auto-merge

#1229 docs: add trace linking note in openai functions example
  cookbook/prompt_management_openai_functions.ipynb
  pages/guides/cookbook/prompt_management_openai_functions.md
Labels: docs, size:XS, auto-merge

#1231 docs: add link to otel docs to otel blog post
  pages/blog/2024-10-opentelemetry-for-llm-observability.mdx
Labels: docs, size:S, auto-merge

#1234 docs: add autogen integration
  cookbook/_routes.json
  cookbook/integration_autogen.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/autogen.md
  pages/guides/cookbook/integration_autogen.md
  public/images/cookbook/integration-autogen/autogen-example-trace.png
Labels: docs, size:L, auto-merge

#1230 docs: add openrouter integration
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/openrouter.mdx
  public/images/docs/openrouter-example-trace/openrouter-example-trace.png
Labels: docs, size:L, auto-merge

#1238 docs: update autogen docs
  cookbook/integration_autogen.ipynb
  pages/docs/integrations/autogen.md
  pages/guides/cookbook/integration_autogen.md
Labels: docs, size:S, auto-merge

#1235 docs: add semantic kernel integration
  cookbook/integration-semantic-kernel.ipynb
  public/images/cookbook/integration-semantic-kernel/sematric-kernel-example-trace.png
Labels: docs, size:L, auto-merge

#1239 docs(api): access via sdks
  pages/docs/api.mdx
Labels: docs, size:M

#1240 docs: add smolagents integration
  cookbook/_routes.json
  cookbook/integration_smolagents.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/smolagents.md
  pages/guides/cookbook/integration_smolagents.md
  public/images/cookbook/integration-smolagents/smolagent_example_trace.png
Labels: documentation, size:L, auto-merge

#1241 docs: add crewai integration
  cookbook/_routes.json
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/crewai.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_crewai.md
  public/images/cookbook/integration_crewai/crewai-example-trace.png
Labels: docs, size:L, auto-merge

#1243 docs: add otel example using the python sdk
  cookbook/_routes.json
  cookbook/otel_integration_python_sdk.ipynb
  pages/docs/opentelemetry/_meta.tsx
  pages/docs/opentelemetry/example-python-sdk.md
  pages/docs/opentelemetry/get-started.mdx
  pages/docs/sdk/python/low-level-sdk.md
  pages/guides/cookbook/otel_integration_python_sdk.md
Labels: docs, size:L, auto-merge

#1245 chore: add collector link
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:XS, auto-merge

#1244 docs(gemini-2.0): model support changelog post
  pages/changelog/2025-02-06-gemini-2-support.mdx
Labels: docs, size:S, auto-merge

#1246 fix: crewai link
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: documentation, size:XS, auto-merge

#1247 docs: edit VAPI page
  pages/docs/integrations/vapi.mdx
Labels: docs, size:XS, auto-merge

#1249 chore: update integration grid on landingpage
  components/home/IntegrationsGrid.tsx
  components/home/img/autogen_icon.svg
  components/home/img/crewai_icon.svg
  components/home/img/huggingface_icon.svg
  components/home/img/microsoft_icon.svg
  components/home/img/opentelemetry_icon.svg
  components/home/img/pydantic-ai_icon.svg
Labels: size:L, auto-merge

#1250 release for jsonpath llm as a judge
  pages/changelog/2025-02-06-llm-as-a-judge-jsonpath.mdx
  pages/docs/scores/model-based-evals.mdx
  public/images/changelog/2025-02-06-eval-config.png
  public/images/docs/eval-config.png
Labels: documentation, size:S, auto-merge

#1253 docs: remove star cta form faq page
  pages/faq/all/api-authentication.mdx
Labels: docs, size:XS, auto-merge

#1254 rate limit docs
  pages/faq/all/api-limits.mdx
Labels: documentation, size:XS, auto-merge

#1256 fix: add redirect for selfhosting
  next.config.mjs
Labels: size:XS, auto-merge

#1257 chore(deps): bump inkeep
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#1258 chore: reduce height of the hero on tall screens
  components/home/Hero.tsx
Labels: size:XS, auto-merge

#1261 docs: add imports to crew ai
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: docs, size:XS, auto-merge

#1262 docs: enrich Otel examples
  cookbook/integration_pydantic_ai.ipynb
  cookbook/otel_integration_openlit.ipynb
  cookbook/otel_integration_openllmetry.ipynb
  pages/docs/integrations/pydantic-ai.md
  pages/docs/opentelemetry/example-openlit.md
  pages/docs/opentelemetry/example-openllmetry.md
  pages/guides/cookbook/integration_pydantic_ai.md
  pages/guides/cookbook/otel_integration_openlit.md
  pages/guides/cookbook/otel_integration_openllmetry.md
Labels: documentation, size:L, auto-merge

#1263 chore: document additional property mapping for otel spans
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:M, auto-merge

#1260 feat: new pricing page component
  components/home/Pricing.tsx
  components/ui/card.tsx
  components/ui/table.tsx
Labels: enhancement, size:XL, auto-merge

#1265 fix: update otel exporter docs to otlphttp
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:XS, auto-merge

#1266 chore: update logos
  components/home/Usage.tsx
Labels: size:M, auto-merge

#1268 Gh readme images
  components-mdx/env-python.mdx
  public/images/docs/github-readme/github-banner.png
  public/images/docs/github-readme/github-deployment-options.png
  public/images/docs/github-readme/github-example-trace.png
  public/images/docs/github-readme/github-integrations.png
Labels: documentation, size:XS, auto-merge

#1270 Gh image
  public/images/docs/github-readme/github-deployment-options.png
  public/images/docs/github-readme/github-feature-overview.png
Labels: size:XS, auto-merge

#1271 docs: update smolagents
  cookbook/integration_smolagents.ipynb
  pages/docs/integrations/smolagents.md
  pages/guides/cookbook/integration_smolagents.md
  public/images/cookbook/integration-smolagents/smolagent_example_trace.png
Labels: documentation, size:M, auto-merge

#1255 docs(select-all): changelog
  pages/changelog/2025-02-11-tables-select-all.mdx
Labels: docs, size:S, auto-merge

#1275 docs: update crewai docs
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: docs, size:XS, auto-merge

#1278 chore: document the used postgres schema
  pages/self-hosting/infrastructure/postgres.mdx
Labels: documentation, size:XS, auto-merge

#1277 docs: add arize ai integration
  cookbook/_routes.json
  cookbook/otel_integration_arize.ipynb
  pages/docs/opentelemetry/_meta.tsx
  pages/docs/opentelemetry/example-arize.md
  pages/guides/cookbook/otel_integration_arize.md
  public/images/cookbook/otel-integration-arize/arize-ai-instrumentation-example-trace.png
Labels: docs, size:L, auto-merge

#1281 docs: add JS LlamaIndex integration
  cookbook/_routes.json
  cookbook/js_integration_llamaindex.ipynb
  pages/docs/integrations/llama-index/_meta.tsx
  pages/docs/integrations/llama-index/example-js-llamaindex.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/js_integration_llamaindex.md
Labels: docs, size:L, auto-merge

#1273 docs: add integration langgraph server
  cookbook/integration_langgraph.ipynb
  pages/docs/integrations/langchain/example-python-langgraph.md
  pages/guides/cookbook/integration_langgraph.md
Labels: documentation, lgtm, size:XXL, auto-merge

#1282 docs: add huntr case study
  pages/faq/all/ai-transparency-remberg-langfuse.mdx
  pages/faq/all/huntr-langfuse-case-study.mdx
  pages/faq/all/mava-langfuse-case-study.mdx
  pages/faq/tag/case-studies.mdx
Labels: docs, size:M, auto-merge

#1251 docs: ad llamaindex workflows integration
  cookbook/_routes.json
  cookbook/integration_llamaindex_workflows.ipynb
  pages/docs/integrations/llama-index/_meta.tsx
  pages/docs/integrations/llama-index/workflows.md
  pages/guides/cookbook/integration_llamaindex_workflows.md
  public/images/cookbook/integration-llamaindex-workflows/llamaindex-workflows-example-trace.png
Labels: docs, size:L, auto-merge

#1283 feat: document redis TLS setup
  pages/self-hosting/configuration.mdx
  pages/self-hosting/infrastructure/cache.mdx
Labels: documentation, size:S, auto-merge

#1284 feat: add otel changelog
  pages/changelog/2025-02-05-public-api-wrapper-sdks.mdx
  pages/changelog/2025-02-14-opentelemetry-tracing.mdx
  public/images/changelog/2025-02-14-opentelemetry-tracing.png
Labels: documentation, lgtm, size:M, auto-merge

#1286 feat: add additional langfuse attributes to otel mapping
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:S, auto-merge

#1288 docs: update DSPy docs
  cookbook/integration_dspy.ipynb
  pages/docs/integrations/dspy.md
  pages/docs/integrations/llama-index/workflows.md
  pages/docs/opentelemetry/example-arize.md
  pages/guides/cookbook/integration_dspy.md
  pages/guides/cookbook/integration_llamaindex_workflows.md
  public/images/cookbook/integration-dspy/dspy-example-trace.png
Labels: documentation, size:M, auto-merge

#1287 feat: document data deletion handling
  pages/docs/_meta.tsx
  pages/docs/data-deletion.mdx
  public/images/docs/delete-filtered-traces.png
  public/images/docs/delete-single-trace.png
  public/images/docs/delete-trace-batch.png
Labels: documentation, size:M, auto-merge

#1290 docs: update Haystack docs
  cookbook/integration_haystack.ipynb
  pages/docs/integrations/haystack/example-python.md
  pages/guides/cookbook/integration_haystack.md
Labels: docs, size:S, auto-merge

#1291 docs: edit intent classification guide
  cookbook/example_intent_classification_pipeline.ipynb
  pages/docs/analytics/example-intent-classification.md
  pages/guides/cookbook/example_intent_classification_pipeline.md
Labels: docs, size:M, auto-merge

#1292 docs: add firecrawl integration
  cookbook/_routes.json
  cookbook/integration_firecrawl.ipynb
  pages/docs/integrations/other/firecrawl.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/integration_firecrawl.md
  public/images/cookbook/integration-firecrawl/firecrawl-example-trace.png
Labels: docs, size:L, auto-merge

#1294 docs: simplify smolagents + arize instrumentation
  cookbook/integration_smolagents.ipynb
  cookbook/otel_integration_arize.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/firecrawl.md
  pages/docs/integrations/smolagents.md
  pages/docs/opentelemetry/example-arize.md
  pages/guides/cookbook/integration_smolagents.md
  pages/guides/cookbook/otel_integration_arize.md
Labels: documentation, size:L, auto-merge

#1299 docs: add agent deep dive blog
  pages/blog/2025-02-20-the-agent-deep-dive-open-deep-research.mdx
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/context.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/costs.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/final-report.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/follow-up-1.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/follow-up.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/gatt.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/learnings.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/serp-queries.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/system-prompt.png
  public/images/blog/2025-02-20-the-agent-deep-dive-open-deep-research/the-agent-deep-dive.png
Labels: documentation, size:L, auto-merge

#1301 docs: add arize to otel page
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:L, auto-merge

#1300 docs: add LiteLLM to comparison pages
  pages/faq/all/best-braintrustdata-alternatives.mdx
  pages/faq/all/best-helicone-alternative.mdx
Labels: documentation, size:XS, auto-merge

#1297 apply model based evals on history
  pages/changelog/2025-02-20-model-based-evals-on-history.mdx
  pages/docs/scores/model-based-evals.mdx
  public/images/changelog/2025-02-20-model-based-evals-on-history.png
  public/images/docs/eval-config.png
Labels: documentation, size:S, auto-merge

#1306 docs: add any llm to playground
  pages/docs/playground.mdx
Labels: documentation, size:XS, auto-merge

#1307 docs: update crew ai docs
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.md
  pages/guides/cookbook/integration_crewai.md
Labels: docs, size:L, auto-merge

#1308 docs: add community hou banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1237 docs: fix python decorators example
  pages/docs/sdk/python/decorators.mdx
Labels: docs, size:XS, auto-merge

#1298 typo and format fix for docs/integrations/openai/python/get-started
  pages/docs/integrations/openai/python/get-started.mdx
Labels: documentation, size:S, auto-merge

#1309 docs: seo routine
  cookbook/integration_langserve.ipynb
  cookbook/integration_litellm_proxy.ipynb
  cookbook/integration_llama_index_posthog_mistral.ipynb
  cookbook/integration_openai_assistants.ipynb
  cookbook/integration_openai_sdk.ipynb
  cookbook/integration_openai_structured_output.ipynb
  cookbook/js_integration_litellm_proxy.ipynb
  cookbook/langfuse_sdk_performance_test.ipynb
  cookbook/python_decorators.ipynb
  pages/about.mdx
  pages/changelog/2024-08-08-openai-structured-outputs.mdx
  pages/docs/data-deletion.mdx
  pages/docs/data-retention.mdx
  pages/docs/integrations/langchain/example-python-langserve.md
  pages/docs/integrations/litellm/example-proxy-js.md
  pages/docs/integrations/litellm/example-proxy-python.md
  pages/docs/integrations/openai/python/assistants-api.md
  pages/docs/integrations/openai/python/examples.md
  pages/docs/integrations/other/openrouter.mdx
  pages/docs/integrations/vercel-ai-sdk.mdx
  pages/docs/sdk/python/example.md
  pages/faq/all/best-braintrustdata-alternatives.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/faq/all/chatbot-analytics.mdx
  pages/faq/all/inviting-in-langfuse.mdx
  pages/faq/all/langsmith-alternative.mdx
  pages/faq/all/link-prompt-management-with-tracing.mdx
  pages/faq/all/llm-analytics-101.mdx
  pages/faq/all/what-is-LCEL.mdx
  pages/faq/index.mdx
  pages/guides/cookbook/integration_langserve.md
  pages/guides/cookbook/integration_litellm_proxy.md
  pages/guides/cookbook/integration_llama_index_posthog_mistral.md
  pages/guides/cookbook/integration_openai_assistants.md
  pages/guides/cookbook/integration_openai_sdk.md
  pages/guides/cookbook/integration_openai_structured_output.md
  pages/guides/cookbook/js_integration_litellm_proxy.md
  pages/guides/cookbook/langfuse_sdk_performance_test.md
  pages/guides/cookbook/python_decorators.md
  pages/index.mdx
  pages/self-hosting/index.mdx
  pages/why.mdx
  public/images/docs/data-retention.png
Labels: documentation, size:L, auto-merge

#1310 docs(changelog): add claude 3.7
  pages/changelog/2025-02-25-claude-3-7-support.mdx
  pages/docs/playground.mdx
Labels: documentation, size:S

#1312 docs(changelog): add google ai studio support
  pages/changelog/2025-02-25-google-ai-studio-support.mdx
Labels: docs, size:S

#1313 docs: faq additions
  .cursor/rules/changelog-posts.mdc
  .cursor/rules/integration-page.mdc
  components/home/Pricing.tsx
  cookbook/_routes.json
  cookbook/integration_dspy.ipynb
  cookbook/integration_langgraph.ipynb
  cookbook/integration_openai_structured_output.ipynb
  cookbook/integration_togetherai.ipynb
  pages/docs/api.mdx
  pages/docs/integrations/langchain/example-python-langgraph.md
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/togetherai.md
  pages/docs/opentelemetry/example-arize.md
  pages/docs/opentelemetry/get-started.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
  pages/faq/all/llm-observability.mdx
  pages/guides/cookbook/integration_dspy.md
  pages/guides/cookbook/integration_langgraph.md
  pages/guides/cookbook/integration_openai_structured_output.md
  pages/guides/cookbook/integration_togetherai.md
  public/images/cookbook/integration-togetherai/togetherai-example-trace.png
Labels: documentation, size:XL, auto-merge

#1315 docs: add changelog for in-product onboarding
  pages/changelog/2025-02-26-in-product-onboarding-screens.mdx
Labels: size:S, auto-merge

#1316 Update banner fab
  theme.config.tsx
Labels: size:S, auto-merge

#1318 chore: document environment in otel docs
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:XS, auto-merge

#1320 docs: add custom attributes to smolagents and arize cookbook
  cookbook/integration_smolagents.ipynb
  cookbook/otel_integration_arize.ipynb
  cookbook/otel_integration_python_sdk.ipynb
  pages/docs/integrations/smolagents.md
  pages/docs/opentelemetry/example-arize.md
  pages/docs/opentelemetry/example-python-sdk.md
  pages/guides/cookbook/integration_smolagents.md
  pages/guides/cookbook/otel_integration_arize.md
  pages/guides/cookbook/otel_integration_python_sdk.md
Labels: documentation, size:L, auto-merge

#1322 docs: update Otel instrumentations
  cookbook/otel_integration_arize.ipynb
  cookbook/otel_integration_openlit.ipynb
  pages/docs/integrations/smolagents.md
  pages/docs/opentelemetry/example-arize.md
  pages/docs/opentelemetry/example-openlit.md
  pages/docs/opentelemetry/example-python-sdk.md
  pages/guides/cookbook/otel_integration_arize.md
  pages/guides/cookbook/otel_integration_openlit.md
Labels: docs, size:XL, auto-merge
