Repository langfuse/langfuse-docs, pull requests merged in 2025-08, with the labels that each got.

#1868 make images on website, docs, blog clickable (only desktop)
  components/Frame.tsx
Labels: enhancement, size:L, auto-merge

#1871 Fel/remove sumup study to launch khanacademy
  components/blog/BlogHeader.tsx
  components/customers/CustomerQuote.tsx
  pages/customers/khan-academy.mdx
  pages/customers/magic-patterns-ai-design-tools.mdx
  public/images/customers/khan-academy/khan-academy-logo.png
  public/images/customers/khan-academy/khanmigo.png
  public/images/customers/khan-academy/walt-wells.jpeg
  public/images/customers/magic-patterns-ai-design-tools/magicpatterns-logo.png
  public/images/customers/sumup/Sumup_logo.png
  public/images/customers/sumup/ana-casado.jpg
  public/images/customers/sumup/luis-dreisbach.jpg
  public/images/customers/sumup/placeholder.jpg
Labels: documentation, size:L, auto-merge

#1872 docs: add google gemini
  cookbook/_routes.json
  cookbook/integration_google_gemini.ipynb
  cookbook/integration_google_vertex_and_gemini.ipynb
  pages/integrations/model-providers/google-gemini.mdx
  public/images/cookbook/integration_gemini/gemini-trace.png
Labels: documentation, size:XL, auto-merge

#1874 docs: add beeai
  cookbook/_routes.json
  cookbook/integration_beeai.ipynb
  pages/integrations/frameworks/beeai.mdx
  public/images/cookbook/integration_beeai/beeai-trace.png
  public/images/integrations/beeai_icon.png
Labels: documentation, size:L, auto-merge

#1870 docs: add google vertex ai
  components/integrations/IntegrationIndex.tsx
  cookbook/_routes.json
  cookbook/integration_byteplus.ipynb
  cookbook/integration_google_vertexai.ipynb
  pages/integrations/model-providers/byteplus.mdx
  pages/integrations/model-providers/google-vertex-ai.md
  pages/integrations/model-providers/google-vertex-ai.mdx
  public/images/cookbook/integration_vertexai/vertexai-trace.png
  public/images/integrations/vertexai_icon.png
Labels: documentation, size:XL, auto-merge

#1867 Docs/truefoundry-integration
  cookbook/_routes.json
  cookbook/integration_truefoundry.ipynb
  next.config.mjs
  pages/integrations/gateways/truefoundry.mdx
  public/images/cookbook/integration_troufoundry/truefoundry-trace.png
  public/images/integrations/truefoundry-logo.png
  public/images/langfuse-trace-tfy.png
  public/images/unified-code-tfy.png
Labels: documentation, size:XL

#1875 docs: add july update
  pages/blog/2025-07-31-langfuse-july-update.mdx
  public/images/blog/2025-07-31-langfuse-july-update/july-update.png
  public/images/blog/2025-07-31-langfuse-july-update/multi-playgroundcl.png
  public/images/blog/2025-07-31-langfuse-july-update/new-docs-and-integration-pagescl.png
  public/images/blog/2025-07-31-langfuse-july-update/remote-experimentscl.png
  public/images/blog/2025-07-31-langfuse-july-update/slack-integrationcl.png
  public/images/blog/2025-07-31-langfuse-july-update/usage-aleartscl.png
Labels: documentation, size:M, auto-merge

#1884 docs: added byteplus
  pages/cn.mdx
  pages/jp.mdx
  pages/kr.mdx
Labels: documentation, size:XS, auto-merge

#1906 docs: annotation queue assignments changelog draft
  pages/changelog/2025-08-07-annotation-queue-assignments.mdx
Labels: documentation, size:M, auto-merge

#1905 fix: add usage alerts issue disclaimer
  pages/docs/administration/usage-alerts.mdx
Labels: documentation, size:XS, auto-merge

#1913 feat: add /.md via rewrite and move the copy as markdown button to this logic
  .cursor/rules/_general-rules.mdc
  .cursor/rules/documentation-pages.mdc
  .gitignore
  components/MainContentWrapper.tsx
  next.config.mjs
  package.json
  pages/api/mcp.ts
  pages/changelog/2025-08-07-markdown-endpoints-and-copy-button.mdx
  scripts/copy_md_sources.js
Labels: enhancement, size:L, auto-merge

#1912 docs(annotation): add queue assignment docs
  pages/changelog/2025-07-28-sessions-in-annotation-queues.mdx
  pages/changelog/2025-08-07-annotation-queue-assignments.mdx
  pages/docs/evaluation/evaluation-methods/annotation.mdx
  public/images/docs/queue_assign_users.png
  public/images/docs/queue_manage_assignments.png
Labels: documentation, size:M, auto-merge

#1916 chore: add trace upsert sharding settings
  pages/self-hosting/infrastructure/cache.mdx
  pages/self-hosting/scaling.mdx
Labels: documentation, size:XS, auto-merge

#1922 sumup case study
  components/customers/CustomerIndex.tsx
  components/shared/EnterpriseLogoGrid.tsx
  pages/customers/sumup.mdx
  public/images/customers/sumup/Sumup-Dark.png
  public/images/customers/sumup/Sumup-Light.png
  public/images/customers/sumup/Sumup_logo.png
  public/images/customers/sumup/sumup_support_screens.png
  public/images/customers/sumup/sumup_tracing_view.png
Labels: documentation, size:L, auto-merge

#1924 docs: move llm connection page
  next.config.mjs
  pages/docs/administration/llm-connection.mdx
  pages/docs/evaluation/dataset-runs/native-run.mdx
  pages/docs/evaluation/evaluation-methods/llm-as-a-judge.mdx
  pages/docs/prompt-management/features/playground.mdx
  pages/faq/all/delete-account-langfuse.mdx
Labels: documentation, size:S, auto-merge

#1925 docs: edit webhooks
  pages/docs/prompt-management/features/webhooks-slack-integrations.mdx
Labels: documentation, size:XS, auto-merge

#1844 docs: update API reference for media
  pages/docs/observability/features/multi-modality.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: docs, size:XS

#1931 docs. improve query via sdk page
  pages/docs/api-and-data-platform/features/query-via-sdk.mdx
Labels: documentation, size:L, auto-merge

#1933 docs: TF update
  cookbook/integration_truefoundry.ipynb
  pages/integrations/gateways/truefoundry.mdx
Labels: documentation, size:XS, auto-merge

#1935 docs: add redirect
  next.config.mjs
Labels: documentation, size:XS, auto-merge

#1948 docs: update OpenWebUI
  pages/integrations/no-code/openwebui.mdx
Labels: documentation, size:XS, auto-merge

#1951 docs: more consistent api doc links
  components-mdx/self-host-features.mdx
  pages/blog/2025-04-30-langfuse-april-update.mdx
  pages/changelog/2025-04-15-admin-apis.mdx
  pages/docs/administration/scim-and-org-api.mdx
  pages/docs/api-and-data-platform/features/public-api.mdx
  pages/self-hosting/_meta.tsx
  pages/self-hosting/configuration.mdx
  pages/self-hosting/health-readiness-endpoints.mdx
  pages/self-hosting/observability.mdx
  pages/self-hosting/organization-management-api.mdx
Labels: documentation, size:L

#1949 Update overview.mdx
  pages/docs/observability/overview.mdx
Labels: documentation, size:XS

#1962 docs: update openweb ui
  pages/integrations/no-code/openwebui.mdx
  public/images/docs/openwebui-example-trace.png
Labels: documentation, size:S, auto-merge

#1963 Update troubleshooting and faq pages
  pages/docs/evaluation/troubleshooting-and-faq.mdx
  pages/docs/observability/sdk/python/troubleshooting-and-faq.mdx
  pages/docs/observability/troubleshooting-and-faq.mdx
  pages/docs/prompt-management/troubleshooting-and-faq.mdx
  pages/security/privacy-faq.mdx
  pages/security/security-faq.mdx
  pages/self-hosting/troubleshooting-and-faq.mdx
Labels: documentation, size:M

#1969 feat(datasets): changelog full text search
  pages/changelog/2025-08-25-full-text-search-for-dataset-items.mdx
Labels: documentation, size:S, auto-merge

#1972 chore: upgrade to node 22
  .github/workflows/ci.yml
  .github/workflows/nextjs_bundle_analysis.yml
  .github/workflows/plain-sync-knowledge-docs.yml
  .github/workflows/update-available-internal-links-cursor-rule.yml
  .nvmrc
  CLAUDE.md
  README.md
  package.json
  pnpm-lock.yaml
Labels: dependencies, size:S, auto-merge

#1974 feat: new public metrics dashboard from metabase
  .env.template
  components-mdx/public-metrics-dashboard.mdx
  components-mdx/public-metrics.mdx
  components/MetabaseDashboard.tsx
  next.config.mjs
  package.json
  pages/about.mdx
  pages/api/metabase-embed.ts
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/blog/2025-06-04-open-sourcing-langfuse-product.mdx
  pages/careers.mdx
  pages/open-source.mdx
  pages/why.mdx
  pnpm-lock.yaml
Labels: enhancement, size:L, auto-merge

#1971 feat(tracing): add further observation types
  components-mdx/observation-types-list.mdx
  pages/changelog/2025-08-27-enhanced-observation-types.mdx
  pages/docs/observability/data-model.mdx
  pages/docs/observability/features/observation-types.mdx
  pages/docs/observability/sdk/python/advanced-usage.mdx
  public/images/changelog/2025-08-27-additional-observation-types.png
  tailwind.config.js
Labels: enhancement, size:L, auto-merge

#1987 docs: change instrumentation of ADK
  cookbook/integration_google_adk.ipynb
  pages/integrations/frameworks/google-adk.mdx
Labels: docs, size:M, auto-merge

#1985 Update repository link for Pipecat integration
  pages/integrations/frameworks/pipecat.mdx
Labels: documentation, size:XS, auto-merge
