Repository langfuse/langfuse-docs, pull requests merged in 2025-01, with the labels that each got.

#1144 chore: add troubleshooting guide for background migrations
  pages/self-hosting/background-migrations.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: documentation, size:S, auto-merge

#1146 feat: document blob storage disks for clickhouse
  next-env.d.ts
  pages/self-hosting/infrastructure/clickhouse.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: documentation, size:L, auto-merge

#1149 docs: fix arize comparison table
  pages/faq/all/best-phoenix-arize-alternatives.mdx
Labels: docs, size:XS, auto-merge

#1150 feat: add documentation for CLICKHOUSE_DB env
  pages/self-hosting/configuration.mdx
  pages/self-hosting/infrastructure/clickhouse.mdx
Labels: documentation, size:S, auto-merge

#1156 feat: add docker compose upgrade guide
  pages/self-hosting/docker-compose.mdx
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: documentation, enhancement, size:M, auto-merge

#1157 docs: add note - numerical scores at llm-as-a-judge
  pages/docs/scores/model-based-evals.mdx
Labels: documentation, size:XS, auto-merge

#1153 docs: add groq cookbook
  cookbook/_routes.json
  cookbook/integration_grpq_sdk.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/groq-sdk.md
  pages/guides/cookbook/integration_grpq_sdk.md
  public/images/cookbook/integration-groq/chained-trace.png
  public/images/cookbook/integration-groq/single-trace-example.png
  public/images/cookbook/integration-groq/streaming-trace.png
Labels: docs, size:XXL, auto-merge

#1154 docs: add hugging face example cookbook
  cookbook/_routes.json
  cookbook/integration_huggingface_openai_sdk.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/huggingface.md
  pages/guides/cookbook/integration_huggingface_openai_sdk.md
  public/images/cookbook/huggingface/huggingface-cookbook-trace-poem.png
  public/images/cookbook/huggingface/huggingface-cookbook-trace-rap.png
  public/images/cookbook/huggingface/huggingface-cookbook-trace-translation.png
Labels: docs, size:XL, auto-merge

#1155 docs: add deepseek cookbook
  cookbook/_routes.json
  cookbook/integration_deepseek_openai_sdk.ipynb
  pages/cn.mdx
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/deepseek.md
  pages/guides/cookbook/integration_deepseek_openai_sdk.md
  public/images/cookbook/integration_deepseek/deepseek-simple-trace.png
  public/images/cookbook/integration_deepseek/deepseek-story-trace.png
Labels: docs, size:XL, auto-merge

#1148 docs: improve environment variable generation methods for docker compose
  pages/self-hosting/docker-compose.mdx
Labels: docs, size:XS

#1143 Add missing import for python langchain integration
  pages/docs/sdk/python/decorators.mdx
Labels: documentation, size:XS

#1141 docs: fix typos in example doc (misspelled `anthropic`)
  pages/docs/sdk/python/example.md
Labels: docs, size:XS

#1140 docs: update Vercel AI SDK instrumentation setup for Next.js 15
  pages/docs/integrations/vercel-ai-sdk.mdx
Labels: docs, size:XS

#1165 docs: change model name in HF guide
  pages/docs/integrations/huggingface.md
Labels: docs, size:XS, auto-merge

#1169 chore: add note on timezone support to docs
  pages/self-hosting/configuration.mdx
  pages/self-hosting/troubleshooting.mdx
Labels: docs, size:S, auto-merge

#1170 chore: add timezone note to CH and PG component docs
  pages/self-hosting/infrastructure/clickhouse.mdx
  pages/self-hosting/infrastructure/postgres.mdx
Labels: documentation, size:S, auto-merge

#1173 docs: remove grammar mistakes in FeatureBento
  components/home/FeatureBento.tsx
Labels: docs, lgtm, size:XS, auto-merge

#1174 docs: add examples to masking page
  pages/docs/tracing-features/masking.mdx
  public/images/docs/masking/masking_example_1.png
  public/images/docs/masking/masking_example_2.png
  public/images/docs/masking/masking_example_3.png
Labels: docs, size:L

#1176 docs(playground): support for gemini-2.0-flash model
  pages/docs/playground.mdx
Labels: docs, size:XS, auto-merge

#1183 fix: add redirect for /docs/integrations/vercel
  next.config.mjs
Labels: docs, size:XS, auto-merge

#1180 docs: metadata on observations
  pages/docs/tracing-features/metadata.mdx
Labels: docs, size:M

#1185 docs: fixed bug in prompt mngt docs
  pages/docs/prompts/get-started.mdx
Labels: docs, size:XS, auto-merge

#1186 feat: add DATABASE_ARGS config option
  pages/self-hosting/configuration.mdx
Labels: documentation, size:XS, auto-merge

#1187 chore: remove azure blob storage beta flag
  pages/self-hosting/infrastructure/blobstorage.mdx
Labels: documentation, size:XS, auto-merge

#1188 chore: update the v2 migration guide to include correct branch
  pages/self-hosting/upgrade-guides/upgrade-v1-to-v2.mdx
Labels: documentation, size:XS, auto-merge

#1190 docs: add note on encryption algo
  pages/self-hosting/encryption.mdx
Labels: documentation, size:XS, auto-merge

#1189 Add encryption at rest docs
  pages/docs/data-security-privacy.mdx
  pages/self-hosting/encryption.mdx
Labels: documentation, size:S, auto-merge

#1191 ci: skip identical ci in merge queue
  .github/workflows/ci.yml
Labels: size:S, auto-merge

#1192 docs: add audit logs to plan comparisons
  components/home/Pricing.tsx
  pages/self-hosting/license-key.mdx
Labels: docs, size:XS, auto-merge

#1179 Add startup discount
  components/home/Pricing.tsx
Labels: enhancement, lgtm, size:S, auto-merge

#1177 docs: ad vercel ai sdk example to datset docs
  pages/docs/datasets/get-started.mdx
Labels: docs, size:M, auto-merge

#1195 chore: add hiring badge to logo on desktop
  components/logo.tsx
  theme.config.tsx
Labels: size:M, auto-merge

#1196 docs: add coval blog pots
  pages/blog/2025-01-22-evaluating-voice-ai-agents.mdx
  public/images/blog/2025-01-22-evaluating-voice-ai-agents/evaluating-voice-ai-agents.png
Labels: documentation, size:L, auto-merge

#1197 docs: add prompt diff feature
  components-mdx/prompt-overview-gifs.mdx
  pages/changelog/2025-01-22-track-changes-between-prompt-versions.mdx
Labels: docs, size:S, auto-merge

#1198 docs: add audit logs changelog
  components/home/Pricing.tsx
  pages/changelog/2025-01-21-audit-logs.mdx
  pages/self-hosting/license-key.mdx
  public/images/changelog/2025-01-21-audit-logs.png
Labels: docs, size:S, auto-merge

#1199 chore: skip vercel build in merge queue and add vercel.json
  scripts/vercel_ignore_build_check.sh
  vercel.json
Labels: size:S, auto-merge

#1203 docs: make checks and auth method configurable across SSO providers
  pages/self-hosting/authentication-and-sso.mdx
Labels: docs, size:M, auto-merge

#1206 docs: add town hall banner
  theme.config.tsx
Labels: docs, size:XS, auto-merge

#1171 docs: nit on vertext ai docs
  cookbook/integration_google_vertex_and_gemini.ipynb
  cookbook/python_decorators.ipynb
  pages/docs/integrations/google-vertex-ai.md
  pages/docs/integrations/huggingface.md
  pages/guides/cookbook/integration_google_vertex_and_gemini.md
  pages/guides/cookbook/python_decorators.md
Labels: documentation, docs, size:S, auto-merge

#1207 feat: document OTEL support for self-hosters
  pages/self-hosting/configuration.mdx
Labels: documentation, size:S, auto-merge

#1209 feat(datasets): changelog CSV upload
  pages/changelog/2025-01-27-Dataset-Items-csv-upload.mdx
Labels: documentation, enhancement, size:S, auto-merge

#1210 docs: add prompt commit changelog; add datasets csv upload gif
  pages/changelog/2025-01-27-Dataset-Items-csv-upload.mdx
  pages/changelog/2025-01-28-prompt-commit-messages.mdx
Labels: documentation, size:S, auto-merge

#1212 docs: change time of town hall
  theme.config.tsx
Labels: docs, size:XS, auto-merge

#1214 docs: remove banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1216 docs: change links to api docs
  pages/changelog/2024-02-19-metrics-api-endpoint.mdx
  pages/cn.mdx
  pages/docs/analytics/daily-metrics-api.mdx
  pages/jp.mdx
  pages/kr.mdx
Labels: documentation, size:S, auto-merge

#1215 feat: add data retention docs and changelog
  components/home/Pricing.tsx
  next-env.d.ts
  pages/changelog/2025-01-30-data-retention.mdx
  pages/docs/_meta.tsx
  pages/docs/data-retention.mdx
  pages/self-hosting/_meta.tsx
  pages/self-hosting/headless-initialization.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
  pages/self-hosting/license-key.mdx
  public/images/changelog/2025-01-30-data-retention.png
Labels: documentation, size:L, auto-merge

#1218 docs: changelog new api reference
  pages/changelog/2025-01-30-new-api-reference.mdx
Labels: docs, size:S, auto-merge

#1219 docs(js-ts): add sampling
  pages/changelog/2025-01-30-sampling-js-ts-sdk.mdx
  pages/docs/sdk/typescript/guide.mdx
  pages/docs/tracing-features/sampling.mdx
Labels: docs, size:L

#1220 docs: changelog for new editor
  pages/changelog/2025-01-30-new-prompt-editor.mdx
  public/images/changelog/2025-01-30-new-prompt-editor.png
Labels: docs, size:S, auto-merge

#1221 chore(deps): bump deps of gh actions for bundlesize workflow
  .github/workflows/nextjs_bundle_analysis.yml
Labels: dependencies, size:XS

#1222 docs: fix broken links
  components-mdx/dependents/python.md
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/careers.mdx
  pages/self-hosting/v2/deployment-guide.mdx
Labels: docs, size:XS, auto-merge

#1224 docs: add goose integration
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/goose.mdx
  pages/docs/integrations/overview.mdx
  public/images/docs/goose-integration/goose-example-trace.png
Labels: docs, size:M, auto-merge

#1225 docs: update goose
  pages/docs/integrations/goose.mdx
  public/images/docs/goose-integration/goose-example-trace.png
Labels: docs, size:M, auto-merge

#1226 docs: changelog o3-mini
  pages/changelog/2025-01-31-o3-mini-support.mdx
  pages/docs/playground.mdx
Labels: docs, size:S, auto-merge
