Repository langfuse/langfuse-docs, pull requests merged in 2025-07, with the labels that each got.

#1721 docs: Add data masking feature to pricing page
  components/home/Pricing.tsx
Labels: enhancement, size:S, auto-merge

#1718 docs: improve the explanation of caching for prompt management.
  pages/docs/prompts/get-started.mdx
Labels: documentation, size:L, auto-merge

#1722 docs: create Langfuse integration guide for Portkey
  cookbook/_routes.json
  cookbook/integration_portkey.ipynb
  pages/docs/integrations/_meta.tsx
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/portkey.mdx
  pages/guides/cookbook/integration_portkey.mdx
  public/images/cookbook/integration-portkey/portkey-example-trace.png
Labels: documentation, size:L, auto-merge

#1726 fix: nimar github
  data/authors.json
Labels: size:XS, auto-merge

#1727 docs: add /find-us page
  pages/_meta.tsx
  pages/events/hacknight2024.mdx
  pages/find-us.mdx
  pages/imprint.mdx
  public/images/imprint/find-us-office-entrance.jpg
  public/images/imprint/find-us-office-map.jpg
Labels: documentation, size:L, auto-merge

#1724 docs: add prompt experiments to core feature overview
  components-mdx/evaluation-overview-gifs.mdx
Labels: documentation, lgtm, size:S, auto-merge

#1730 Add changelog entry for search bar on prompts
  pages/changelog/2025-07-01-search-for-prompts.mdx
  pages/docs/prompts/get-started.mdx
Labels: documentation, size:S, auto-merge

#1732 dashboard tool analytics use case
  pages/docs/analytics/custom-dashboards.mdx
Labels: documentation, size:XS, auto-merge

#1733 chore: add claude.md file
  CLAUDE.md
Labels: auto-merge

#1734 chore(prompts): add message placeholder example code
  pages/docs/prompts/get-started.mdx
  src/github-stars.ts
Labels: documentation, size:M, auto-merge

#1738 docs(changelog): gemini 2.5 support
  pages/changelog/2025-07-03-gemini-2.5-support.mdx
Labels: documentation, size:S

#1746 Add internal links to bullet points
  pages/blog/2025-06-30-langfuse-june-update.mdx
Labels: documentation, size:XS, auto-merge

#1745 fix: add roles CTA further up
  pages/careers.mdx
Labels: documentation, size:S, auto-merge

#1747 Add installation instructions for MCP server to LLM.txt
  scripts/generate_llms_txt.js
Labels: documentation, size:XS, auto-merge

#1749 chore: add links to careers page culture table
  components-mdx/public-metrics.mdx
  components/customers/ImpactChart.tsx
  pages/careers.mdx
Labels: documentation, size:L, auto-merge

#1752 docs: update autogen cookbook
  cookbook/integration_autogen.ipynb
  pages/docs/integrations/autogen.mdx
  pages/guides/cookbook/integration_autogen.mdx
Labels: documentation, size:M, auto-merge

#1755 Add sitemap link verification check
  .github/workflows/ci.yml
  package.json
  scripts/check-sitemap-links.js
Labels: enhancement, size:L

#1757 docs: fix on pricing page
  components/home/Pricing.tsx
Labels: docs, size:XS, auto-merge

#1759 docs: update langgraph cookbook
  cookbook/example_langgraph_agents.ipynb
  pages/docs/integrations/langchain/example-langgraph-agents.mdx
  pages/docs/integrations/strands-agents.mdx
  pages/guides/cookbook/example_langgraph_agents.mdx
  pages/guides/cookbook/integration_aws_strands_agents.mdx
Labels: documentation, size:L, auto-merge

#1761 docs: data retention
  pages/docs/data-retention.mdx
Labels: docs, size:XS, auto-merge

#1764 fix: add version constraints for vercel-ai-sdk implementation
  pages/docs/integrations/vercel-ai-sdk.mdx
Labels: documentation, size:XS, auto-merge

#1769 docs: update crewai notebook
  cookbook/integration_crewai.ipynb
  pages/docs/integrations/crewai.mdx
  pages/guides/cookbook/integration_crewai.mdx
Labels: documentation, size:M, auto-merge

#1768 docs: webhooks for prompts
  pages/changelog/2025-07-11-prompt-version-webhooks.mdx
  pages/docs/prompts/get-started.mdx
  public/images/changelog/2025-07-11-webhook-changelog.png
  public/images/docs/webhook-action.png
  public/images/docs/webhook-trigger.png
Labels: documentation, size:L, auto-merge

#1771 refactor: use uv for notebook script to reduce dependency issues
  .github/workflows/ci.yml
  CLAUDE.md
  README.md
  poetry.toml
  pyproject.toml
  scripts/update_cookbook_docs.sh
Labels: size:M

#1774 feat: add link checking for href links in components
  pages/docs/integrations/llama-index/deprecated/deprecated-llama-index-callback.mdx
  pages/docs/integrations/llama-index/deprecated/get-started.mdx
  scripts/check-links.js
Labels: enhancement, size:L, auto-merge

#1777 ci: Add consolidated ci check
  .github/workflows/ci.yml
Labels: size:S, auto-merge

#1783 chore: add metadata mapping clarification for OTel
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:S, auto-merge

#1787 docs: update demo page
  pages/docs/demo.mdx
Labels: documentation, size:S, auto-merge

#1788 docs: update banner town hall
  theme.config.tsx
Labels: docs, size:XS, auto-merge

#1792 Add Langdock integration documentation page
  pages/integrations/no-code/langdock.mdx
  public/images/docs/langdock_1_enable_assistant_logs.png
  public/images/docs/langdock_2_enable_tracing_for_assistant.png
  public/images/integrations/langdock_icon.svg
Labels: documentation, size:M, auto-merge

#1793 chore: add encryption note on postgres, redis, blob store
  pages/self-hosting/encryption.mdx
Labels: documentation, size:XS, auto-merge

#1794 feat: wall-of-love on website
  components/Header.tsx
  components/home/WallOfLove.tsx
  components/home/index.tsx
  data/testimonials.ts
  public/images/producthunt.png
  public/images/walloflove/FeliksGhazaryan.avif
  public/images/walloflove/FelixGuo.avif
  public/images/walloflove/FenilSuchak.avif
  public/images/walloflove/MaxPrilutskiy.jpg
  public/images/walloflove/PhilippHoevelmann.jpeg
  public/images/walloflove/RomanGeugelin.avif
  public/images/walloflove/boris.avif
  public/images/walloflove/davewilson.avif
  public/images/walloflove/dmitriy.jpg
  public/images/walloflove/fengjiaopeng.avif
  public/images/walloflove/grantsloane.jpeg
  public/images/walloflove/jackson.avif
  public/images/walloflove/manuhortet.avif
  public/images/walloflove/maurice.avif
  public/images/walloflove/nadeesha.png
  public/images/walloflove/naxsh.jpg
  public/images/walloflove/othmane.jpg
  public/images/walloflove/vicstor.jpg
  public/images/xcom.png
Labels: enhancement, size:L, auto-merge

#1797 fix: small fixes, typo on wall of love & spacing of docs feedback com…
  components/MainContentWrapper.tsx
  components/home/WallOfLove.tsx
Labels: documentation, size:XS, auto-merge

#1798 Felix/lfe 5828/social proof on checkout
  components/home/Pricing.tsx
  components/home/components/TrustedBy.tsx
  data/trusted-by.ts
  public/images/customers/picing-logos/brevo.png
  public/images/customers/picing-logos/cincsystems.png
  public/images/customers/picing-logos/close.io.png
  public/images/customers/picing-logos/dixa.png
  public/images/customers/picing-logos/draftbit.png
  public/images/customers/picing-logos/godaddy.png
  public/images/customers/picing-logos/hgcapital.png
  public/images/customers/picing-logos/khanacademy.png
  public/images/customers/picing-logos/knowunity.png
  public/images/customers/picing-logos/kombo.png
  public/images/customers/picing-logos/prezi.png
  public/images/customers/picing-logos/sumup.png
  public/images/customers/picing-logos/tana.png
  public/images/customers/picing-logos/twilio.png
Labels: enhancement, size:L, auto-merge

#1803 fix(tracing): data model link
  pages/docs/tracing-features/metadata.mdx
Labels: documentation, size:XS, auto-merge

#1808 docs: add self-serve research
  pages/research.mdx
Labels: docs, size:S, auto-merge

#1809 chore: update platform & data feature pages and structure
  pages/docs/_meta.tsx
  pages/docs/administration/_meta.tsx
  pages/docs/data-analytics/_meta.tsx
  pages/docs/data-analytics/features/_meta.tsx
  pages/docs/data-analytics/features/custom-dashboards.mdx
  pages/docs/data-analytics/features/export-data.mdx
  pages/docs/data-analytics/features/fine-tuning.mdx
  pages/docs/data-analytics/features/metrics-api.mdx
  pages/docs/data-analytics/features/public-api.mdx
  pages/docs/data-analytics/features/query-traces.mdx
  pages/docs/data-analytics/overview.mdx
  pages/docs/observability/features/_meta.tsx
  pages/docs/platform/features/fine-tuning.mdx
  pages/docs/platform/overview.mdx
  public/images/docs/blob-storage.png
  public/images/docs/llm-analytics.png
  public/images/docs/open-data-platform-light.png
Labels: documentation, size:L

#1811 Add mcp-use integration page
  pages/integrations/other/mcp-use.mdx
  public/images/integrations/mcp-use_icon.svg
Labels: documentation, size:L

#1813 Automated grammar correction for docs
  components-mdx/tracing-overview-gifs.mdx
  pages/blog/2024-06-monitoring-llm-security.mdx
  pages/blog/2024-11-llm-product-management.mdx
  pages/changelog/2024-01-29-custom-model-prices.mdx
  pages/changelog/2025-01-22-track-changes-between-prompt-versions.mdx
  pages/changelog/2025-02-25-google-ai-studio-support.mdx
  pages/docs/administration/data-deletion.mdx
  pages/docs/evaluation/get-started/offline.mdx
  pages/docs/evaluation/get-started/online.mdx
  pages/docs/index.mdx
  pages/docs/observability/sdk/python/low-level-sdk.md
  pages/docs/observability/sdk/python/sdk-v3.mdx
  pages/docs/observability/sdk/typescript/example-notebook.md
  pages/docs/observability/sdk/typescript/guide.mdx
  pages/faq/all/managing-different-environments.mdx
  pages/guides/cookbook/example_intent_classification_pipeline.md
  pages/guides/cookbook/integration_crewai.mdx
  pages/guides/cookbook/integration_gradio_chatbot.md
  pages/guides/cookbook/integration_langgraph.mdx
  pages/guides/cookbook/integration_llama_index.mdx
  pages/guides/cookbook/integration_openai_sdk.md
  pages/guides/cookbook/integration_semantic_kernel.mdx
  pages/guides/cookbook/js_langfuse_sdk.md
  pages/guides/cookbook/python_sdk_low_level.md
  pages/integrations/frameworks/crewai.mdx
  pages/integrations/frameworks/llamaindex.mdx
  pages/integrations/frameworks/pipecat.mdx
  pages/integrations/frameworks/quarkus-langchain4j.mdx
  pages/integrations/frameworks/semantic-kernel.mdx
  pages/integrations/native/opentelemetry.mdx
  pages/integrations/other/gradio.md
  pages/library/index.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
  pages/self-hosting/infrastructure/clickhouse.mdx
  pages/self-hosting/ui-customization.mdx
Labels: documentation, size:M

#1815 add redirects for all moved pages
  .github/workflows/ci.yml
  next.config.mjs
Labels: documentation, size:M

#1816 docs(fixes): new structure
  pages/docs/index.mdx
  pages/docs/observability/features/_meta.tsx
  pages/docs/observability/features/tags.mdx
  pages/docs/observability/features/users.mdx
  pages/docs/observability/get-started.mdx
  pages/docs/prompt-management/overview.mdx
Labels: docs, size:M

#1817 fix: imprvoe evals / platform links
  .cursor/rules/available-internal-links.mdc
  .cursor/rules/integration-page.mdc
  components-mdx/get-started/next-steps.mdx
  data/generated/contributors.json
  next.config.mjs
  pages/changelog/2024-07-11-non-numeric-scores-api.mdx
  pages/docs/api-and-data-platform/features/query-via-sdk.mdx
  pages/docs/evaluation/_meta.tsx
  pages/docs/evaluation/data-model.mdx
  pages/docs/evaluation/features/_meta.tsx
  pages/docs/evaluation/features/datasets.mdx
  pages/docs/evaluation/features/evaluation-methods/custom-scores.mdx
  pages/docs/evaluation/features/evaluation-methods/llm-as-a-judge.mdx
  pages/docs/evaluation/features/evaluation-methods/user-feedback.mdx
  pages/docs/evaluation/features/experiment-comparison.mdx
  pages/docs/evaluation/features/prompt-experiments.mdx
  pages/docs/evaluation/overview.mdx
Labels: documentation, size:M

#1818 chore: improve prompt docs
  .claude/settings.local.json
  next.config.mjs
  pages/docs/prompt-management/features/github-actions-webhook.mdx
  pages/docs/prompt-management/features/github-integration.mdx
Labels: documentation, size:L

#1819 docs: add anthropic integration page
  cookbook/_routes.json
  cookbook/integration_anthropic.ipynb
  pages/guides/cookbook/integration_anthropic.mdx
  pages/integrations/model-providers/anthropic.mdx
  public/images/cookbook/integration_anthropic/anthropic-example-trace.png
  public/images/integrations/anthropic_icon.png
Labels: docs, size:XL, auto-merge

#1824 docs: add Langchain (Python SDK v3) to metadata and trace_id pages
  pages/docs/observability/features/masking.mdx
  pages/docs/observability/features/metadata.mdx
  pages/docs/observability/features/trace-ids-and-distributed-tracing.mdx
  pages/docs/observability/features/url.mdx
Labels: docs, size:L, auto-merge

#1827 Docs: small fixes
  pages/docs/observability/features/_meta.tsx
  pages/security/hipaa.mdx
Labels: documentation, size:XS, auto-merge

#1829 feat: add Okta setup guide
  pages/docs/administration/scim-and-org-api.mdx
  pages/self-hosting/authentication-and-sso.mdx
Labels: documentation, size:M, auto-merge

#1830 docs: remove banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1835 docs: update anthropic page
  cookbook/integration_anthropic.ipynb
  pages/guides/cookbook/integration_anthropic.mdx
  pages/integrations/model-providers/anthropic.mdx
Labels: documentation, size:L, auto-merge

#1831 docs: update faq sections in docs
  pages/docs/evaluation/troubleshooting-and-faq.mdx
  pages/docs/observability/troubleshooting-and-faq.mdx
  pages/docs/prompt-management/overview.mdx
  pages/docs/prompt-management/troubleshooting-and-faq.mdx
  pages/faq/all/ai-research-assistant-monitoring.mdx
  pages/faq/all/api-limits.mdx
  pages/faq/all/best-braintrustdata-alternatives.mdx
  pages/faq/all/best-helicone-alternative.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/faq/all/cannot-see-organization.mdx
  pages/faq/all/challenges-of-building-llm-applications.mdx
  pages/faq/all/chatbot-analytics.mdx
  pages/faq/all/costs-tokens-langfuse.mdx
  pages/faq/all/custom-langchain-run-names.mdx
  pages/faq/all/cutting-costs.mdx
  pages/faq/all/delete-account-langfuse.mdx
  pages/faq/all/empty-trace-input-and-output.mdx
  pages/faq/all/error-handling-and-timeouts.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
  pages/faq/all/forgot-password.mdx
  pages/faq/all/how-to-measure-prompt-performance.mdx
  pages/faq/all/inviting-in-langfuse.mdx
  pages/faq/all/langfuse-support.mdx
  pages/faq/all/langsmith-alternative.mdx
  pages/faq/all/link-prompt-management-with-tracing.mdx
  pages/faq/all/llm-analytics-101.mdx
  pages/faq/all/llm-observability.mdx
  pages/faq/all/managing-different-environments.mdx
  pages/faq/all/monitoring-ai-generated-content.mdx
  pages/faq/all/openai-assistant-api.mdx
  pages/faq/all/packages-depending-on-langfuse.mdx
  pages/faq/all/report-feedback-bug.mdx
  pages/faq/all/self-hosting-langfuse.mdx
  pages/faq/all/ten-reasons-to-use-langfuse.mdx
  pages/faq/all/what-is-LCEL.mdx
  pages/faq/all/what-is-prompt-engineering.mdx
  pages/faq/all/where-are-langfuse-api-keys.mdx
  pages/faq/all/where-is-my-project.mdx
Labels: documentation, size:L, auto-merge

#1839 docs: add changelog entry for triggering remote custom experiments from UI
  pages/changelog/2025-07-24-remote-experiment-triggers.mdx
Labels: documentation, size:M, auto-merge

#1842 Improve pricing page clarity and design
  components/home/Pricing.tsx
Labels: documentation, size:XS, auto-merge

#1841 Add livekit integration page
  pages/changelog/2025-07-25-livekit-integration.mdx
  pages/integrations/frameworks/livekit.mdx
  public/images/changelog/2025-07-25-livekit-integration.png
  public/images/docs/livekit-trace.png
  public/images/integrations/livekit_icon.svg
Labels: documentation, size:L, auto-merge

#1840 docs add security faq content
  pages/security/security-faq.mdx
Labels: documentation, size:S, auto-merge

#1849 major changes to custom evals (mostly simplification)
  pages/docs/evaluation/evaluation-methods/custom-scores.mdx
  pages/docs/evaluation/evaluation-methods/data-model.mdx
  pages/faq/all/user-feedback.mdx
Labels: documentation, size:L

#1850 docs: update-openai-agents
  cookbook/integration_openai-agents.ipynb
  pages/guides/cookbook/integration_anthropic.mdx
  pages/guides/cookbook/integration_openai-agents.mdx
  pages/integrations/frameworks/openai-agents.mdx
  pages/integrations/model-providers/anthropic.mdx
Labels: documentation, size:L, auto-merge

#1852 docs: update openai agents cookbook
  cookbook/integration_openai-agents.ipynb
  pages/guides/cookbook/integration_openai-agents.mdx
  pages/integrations/frameworks/openai-agents.mdx
Labels: documentation, size:S, auto-merge

#1853 Fel/review/feedback/datasetruns
  components-mdx/datasets-create-dataset.mdx
  components-mdx/datasets-datamodel.mdx
  pages/docs/evaluation/dataset-runs/data-model.mdx
  pages/docs/evaluation/dataset-runs/datasets.mdx
  pages/docs/evaluation/dataset-runs/run-via-sdk.mdx
  pages/docs/evaluation/dataset-runs/run-via-ui.mdx
  public/images/docs/configure_dataset_run.png
  public/images/docs/create_dataset.png
  public/images/docs/navigate-to-dataset.png
  public/images/docs/trigger-process-2.png
  public/images/docs/trigger-process.png
Labels: documentation, size:L

#1857 feat: add usage alerts documentation
  pages/changelog/2025-07-30-usage-alerts.mdx
  pages/docs/administration/usage-alerts.mdx
  pages/faq/all/cutting-costs.mdx
Labels: documentation, size:M, auto-merge

#1859 Add documentation for integrating Vercel AI Gateway
  next.config.mjs
  pages/faq/all/llm-connection.mdx
  pages/integrations/gateways/vercel-ai-gateway.mdx
  public/images/integrations/vercel_ai_gateway_icon.svg
Labels: documentation, size:L

#1863 docs: docs and changelog updates
  pages/changelog/2025-07-01-pivot-tables-custom-dashboards.mdx
  pages/changelog/2025-07-01-search-for-prompts.mdx
  pages/changelog/2025-07-02-prompt-management-placeholders.mdx
  pages/changelog/2025-07-03-gemini-2.5-support.mdx
  pages/changelog/2025-07-06-n8n-node-for-langfuse-prompts.mdx
  pages/changelog/2025-07-11-prompt-version-webhooks.mdx
  pages/changelog/2025-07-22-full-text-search-for-prompts.mdx
  pages/changelog/2025-07-24-remote-experiment-triggers.mdx
  pages/changelog/2025-07-25-livekit-integration.mdx
  pages/changelog/2025-07-28-playground-side-by-side.mdx
  pages/changelog/2025-07-28-sessions-in-annotation-queues.mdx
  pages/changelog/2025-07-30-slack-prompt-notifications.mdx
  pages/changelog/2025-07-30-usage-alerts.mdx
  pages/docs/prompt-management/features/playground.mdx
  pages/docs/prompt-management/features/webhooks-slack-integrations.mdx
  public/images/docs/playground-model-selection.png
  public/images/docs/playground-variables.png
  public/images/docs/slack-connection-auth-init.png
  public/images/docs/slack-connection-channel-select.png
  public/images/docs/webhook-create.png
  public/images/docs/webhook-navigation.png
Labels: documentation, size:L, auto-merge

#1864 introduce "native and remote" Dataset Runs
  next.config.mjs
  pages/docs/evaluation/dataset-runs/_meta.tsx
  pages/docs/evaluation/dataset-runs/datasets.mdx
  pages/docs/evaluation/dataset-runs/native-run.mdx
  pages/docs/evaluation/dataset-runs/remote-run.mdx
  pages/docs/evaluation/evaluation-methods/custom-scores.mdx
  pages/docs/evaluation/evaluation-methods/llm-as-a-judge.mdx
  pages/docs/evaluation/overview.mdx
Labels: enhancement, size:L, auto-merge
