Repository langfuse/langfuse-docs, pull requests merged in 2025-10, with the labels that each got.

#2134 Add context engineering article to prompts
  pages/library/index.mdx
Labels: size:XS

#2139 Apply text balance to team sentence
  components/home/Usage.tsx
  components/home/UsersMarquee.tsx
Labels: size:XS

#2140 Add zapier integration docs
  pages/integrations/other/zapier.mdx
  public/images/integrations/zapier_icon.png
Labels: documentation, size:M, auto-merge

#2142 Update changelog image
  public/images/changelog/2025-07-25-livekit-integration.png
  public/images/changelog/2025-09-30-natural-language-filters.png
  public/images/changelog/2025-09-30-structured-output-prompt-experiments.png
  public/images/docs/llm-connection-provider-options.png
  public/images/docs/slack-prompt-message.png
Labels: documentation, size:XS, auto-merge

#2145 fix(costs): add reference to observation types
  pages/docs/observability/features/token-and-cost-tracking.mdx
Labels: documentation, size:XS, auto-merge

#2148 Update Langfuse docs with Mastra integration
  pages/integrations/frameworks/mastra.mdx
Labels: documentation, size:L, auto-merge

#2091 feat: remove collab button in Deno notebooks
  components/NotebookBanner.tsx
Labels: size:M

#2104 Fix TS API client example
  pages/docs/api-and-data-platform/features/public-api.mdx
Labels: bug, size:XS, auto-merge

#2151 feat: add /api/md-to-pdf route to allow downloading of markdown files from docs
  components/MainContentWrapper.tsx
  package.json
  pages/api/md-to-pdf.ts
  pages/cookie-policy.mdx
  pages/privacy.mdx
  pnpm-lock.yaml
  scripts/check-links.js
Labels: enhancement, size:L, auto-merge

#2153 Update docs with new observation types
  pages/blog/update-202-INVALID.md
  pages/blog/update-2023-08.mdx
  pages/blog/update-2023-09.mdx
  pages/changelog/2023-09-25-datasets.mdx
  pages/docs/evaluation/experiments/experiments-via-sdk.mdx
  pages/docs/observability/features/releases-and-versioning.mdx
  pages/docs/observability/sdk/python/overview.mdx
  pages/guides/cookbook/example_data_migration.md
  pages/integrations/native/opentelemetry.mdx
Labels: documentation, size:S, auto-merge

#2156 chore: remove troubleshooting/faq from self-hosting index
  components-mdx/self-host-help-footer.mdx
  pages/self-hosting/index.mdx
Labels: documentation, size:S, auto-merge

#2158 feat: add playlist features to /watch-demo
  components/WatchDemo.tsx
  components/walkthroughs/WatchWalkthroughsCards.tsx
  components/walkthroughs/WatchWalkthroughsPage.tsx
  components/walkthroughs/constants.ts
  pages/changelog/2025-08-26-new-end-to-end-walkthrough.mdx
  pages/enterprise.mdx
  pages/guides/index.mdx
  pages/guides/videos/index.mdx
  pages/watch-demo.mdx
Labels: enhancement, size:XL, auto-merge

#2163 refactor: pricing page cleanup
  components/home/index.tsx
  components/home/pricing/PricingCalculator.tsx
  components/home/pricing/PricingDiscounts.tsx
  components/home/pricing/PricingFAQ.tsx
  components/home/pricing/PricingTable.tsx
  components/home/pricing/index.tsx
  pages/pricing-self-host.mdx
  pages/pricing.mdx
Labels: size:XXL, auto-merge
