Repository langfuse/langfuse-docs, pull requests merged in 2025-04, with the labels that each got.

#1409 docs: add march update to blog
  pages/blog/2025-03-31-langfuse-march-update.mdx
  public/images/blog/2025-03-31-langfuse-march-update/march-25-new-integrations.png
  public/images/blog/2025-03-31-langfuse-march-update/march-update.png
  public/images/blog/2025-03-31-langfuse-march-update/new-ui.gif
Labels: docs, size:M, auto-merge

#1408 docs: misc edits
  .cursor/rules/embed-video.mdc
  cookbook/integration_instructor.ipynb
  pages/docs/integrations/instructor.md
  pages/docs/integrations/langchain/tracing.mdx
  pages/guides/cookbook/integration_instructor.md
  public/images/docs/instructor-trace.png
Labels: docs, size:L, auto-merge

#1407 Add Cleanlab TLM integration
  cookbook/_routes.json
  cookbook/evaluation_of_llms_with_cleanlab.ipynb
  pages/docs/integrations/other/_meta.tsx
  pages/docs/integrations/other/cleanlab.md
  pages/docs/integrations/overview.mdx
  pages/guides/cookbook/evaluation_of_llms_with_cleanlab.md
  public/images/cookbook/integration-cleanlab/tlm_trust_scores.png
  public/images/cookbook/integration-cleanlab/tlm_trust_scores_explanation.png
Labels: documentation, size:XXL

#1352 Prevent unwanted newlines in base64 output by using `-w 0` flag
  pages/docs/opentelemetry/get-started.mdx
Labels: documentation, size:XS, auto-merge

#1411 chore: add additional blobstorage export formats
  pages/docs/query-traces.mdx
Labels: documentation, size:XS, auto-merge

#1412 chore: add note on redis permissions
  pages/self-hosting/infrastructure/cache.mdx
Labels: documentation, size:XS, auto-merge

#1413 chore: remove speedinsights
  package.json
  pages/_app.tsx
  pnpm-lock.yaml
Labels: dependencies, size:XS, auto-merge

#1419 feat(blog): add filter by tag
  components/blog/BlogIndex.tsx
  components/ui/button.tsx
  pages/blog/2024-04-introducing-langfuse-2.0.mdx
  pages/blog/2024-06-monitoring-llm-security.mdx
  pages/blog/2024-07-ai-agent-observability-with-langfuse.mdx
  pages/blog/2024-08-what-is-langchain.mdx
  pages/blog/2024-09-langfuse-proxy.mdx
  pages/blog/2024-10-observability-in-multi-step-llm-systems.mdx
  pages/blog/2024-10-opentelemetry-for-llm-observability.mdx
  pages/blog/2024-11-llm-product-management.mdx
  pages/blog/2024-12-langfuse-v3-infrastructure-evolution.mdx
  pages/blog/2025-01-22-evaluating-voice-ai-agents.mdx
  pages/blog/2025-02-20-the-agent-deep-dive-open-deep-research.mdx
  pages/blog/2025-03-04-llm-evaluation-101-best-practices-and-challenges.mdx
  pages/blog/2025-03-19-ai-agent-comparison.mdx
  pages/blog/langchain-integration.mdx
  pages/blog/qa-chatbot-for-langfuse-docs.mdx
  pages/blog/showcase-llm-chatbot.mdx
  pages/blog/uptrain-integration.mdx
Labels: enhancement, size:L, auto-merge

#1420 chore: add note on parallel v2 and v3 operations
  pages/self-hosting/upgrade-guides/upgrade-v2-to-v3.mdx
Labels: documentation, size:XS, auto-merge

#1426 docs: add cookbook on synthetic dataset generation
  cookbook/_routes.json
  cookbook/example_synthetic_datasets.ipynb
  pages/docs/datasets/_meta.tsx
  pages/docs/datasets/example-synthetic-datasets.md
  pages/guides/cookbook/example_synthetic_datasets.md
  public/images/cookbook/example-synthetic-datasets/deepeval-dataset.png
  public/images/cookbook/example-synthetic-datasets/hf-dataset.png
  public/images/cookbook/example-synthetic-datasets/hf-generator.png
  public/images/cookbook/example-synthetic-datasets/openai-dataset.png
  public/images/cookbook/example-synthetic-datasets/ragas-dataset.png
Labels: docs, size:XL, auto-merge

#1425 docs: update roadmap (2025 q2)
  pages/docs/roadmap.mdx
Labels: docs, size:M, auto-merge

#1431 docs: nits
  pages/blog/2024-07-ai-agent-observability-with-langfuse.mdx
  pages/docs/roadmap.mdx
Labels: docs, size:S, auto-merge

#1428 docs: add self-serve security reports
  pages/changelog/2024-04-30-SOC-2-Type-2-certification.mdx
  pages/docs/data-security-privacy.mdx
  pages/faq/all/fifteen-questions-langfuse-answered.mdx
  pages/faq/all/ten-reasons-to-use-langfuse.mdx
  pages/self-hosting/encryption.mdx
  pages/self-hosting/v2/deployment-guide.mdx
Labels: docs, size:S, auto-merge

#1432 docs: fix langflow Docker compose
  pages/docs/integrations/langflow.mdx
Labels: documentation, size:L, auto-merge

#1434 feat: switch from crisp to plain for support chat
  .env.template
  components/MainContentWrapper.tsx
  components/inkeep/useInkeepSettings.ts
  components/supportChat/chat.tsx
  components/supportChat/index.tsx
  package.json
  pages/_app.tsx
  pnpm-lock.yaml
Labels: enhancement, size:L, auto-merge

#1435 feat: generate sitemap for github discussions
  .github/workflows/update-github-discussions.yml
  public/github-discussions-sitemap.xml
  scripts/load_github_discussions.py
  src/langfuse_github_discussions.json
Labels: enhancement, size:M, auto-merge

#1436 feat: cron job to trigger indexing of knowledge docs
  .github/workflows/plain-sync-knowledge-docs.yml
Labels: size:M

#1438 docs: add video api keys
  pages/faq/all/where-are-langfuse-api-keys.mdx
Labels: documentation, size:XS, auto-merge

#1437 feat: document org and admin APIs
  pages/changelog/2025-04-15-admin-apis.mdx
  pages/docs/_meta.tsx
  pages/docs/admin-api.mdx
  pages/self-hosting/_meta.tsx
  pages/self-hosting/organization-management-api.mdx
Labels: documentation, size:L, auto-merge

#1439 Seo fixes q2
  .cursor/rules/embed-videos.mdc
  components/FooterMenu.tsx
  components/home/Integrations.tsx
  components/home/IntegrationsGrid.tsx
  cookbook/integration_amazon_bedrock.ipynb
  cookbook/integration_google_vertex_and_gemini.ipynb
  cookbook/integration_mirascope.ipynb
  pages/blog/2024-05-haystack-integration.mdx
  pages/blog/2024-11-most-used-oss-llmops.mdx
  pages/blog/announcing-our-seed-round.mdx
  pages/blog/update-2023-07.mdx
  pages/blog/update-2023-09.mdx
  pages/careers.mdx
  pages/changelog/2024-05-16-mirascope-integration.mdx
  pages/changelog/2024-08-15-deployment-as-porter-add-on.mdx
  pages/docs/ask-ai.mdx
  pages/docs/get-started.mdx
  pages/docs/integrations/bedrock/amazon-bedrock.md
  pages/docs/integrations/databricks/use-with-playground-and-evals.mdx
  pages/docs/integrations/google-vertex-ai.md
  pages/docs/integrations/langchain/example-python.md
  pages/docs/integrations/mirascope/example-python.md
  pages/docs/integrations/overview.mdx
  pages/docs/integrations/vercel-ai-sdk.mdx
  pages/enterprise.mdx
  pages/faq/all/best-braintrustdata-alternatives.mdx
  pages/faq/all/best-helicone-alternative.mdx
  pages/faq/all/best-phoenix-arize-alternatives.mdx
  pages/faq/all/chatbot-analytics.mdx
  pages/faq/all/langsmith-alternative.mdx
  pages/guides/cookbook/integration_amazon_bedrock.md
  pages/guides/cookbook/integration_google_vertex_and_gemini.md
  pages/guides/cookbook/integration_mirascope.md
  pages/guides/videos/beginners-guide-to-rag-evaluation.mdx
  pages/guides/videos/introducing-langfuse-2.0.mdx
  pages/self-hosting/infrastructure/blobstorage.mdx
  pages/watch-demo.mdx
Labels: documentation, size:L

#1443 feat: allow to download logo white
  components/LogoContextMenu.tsx
  public/langfuse_logo_white.png
Labels: enhancement, size:S, auto-merge

#1446 docs: support for openai o3, o4-mini
  pages/changelog/2025-04-16-o3-o4-mini-support.mdx
  pages/docs/playground.mdx
Labels: docs, size:M, auto-merge

#1451 feat: add copy markdown button to docs pages
  components/MainContentWrapper.tsx
  pages/changelog/2025-04-17-copy-as-markdown.mdx
Labels: documentation, enhancement, size:L, auto-merge

#1454 chore: add /request-security-docs redirect
  next.config.mjs
  pages/docs/data-security-privacy.mdx
Labels: documentation, size:S, auto-merge

#1453 feat: add trial request form to pricing page
  components/home/Pricing.tsx
  next.config.mjs
Labels: enhancement, size:M, auto-merge

#1455 chore: mark custom dashboards as beta on self-hosted
  pages/docs/analytics/custom-dashboards.mdx
Labels: documentation, size:XS, auto-merge

#1458 feat: improve visual structure of demo booking
  components/scheduleDemo.tsx
  components/ui/breadcrumb.tsx
  components/ui/separator.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement, size:L, auto-merge

#1448 docs: update open-source page
  pages/docs/open-source.mdx
Labels: docs, size:L, auto-merge

#1460 docs: add env example
  cookbook/integration_openai-agents.ipynb
  pages/docs/integrations/openaiagentssdk/openai-agents.md
  pages/guides/cookbook/integration_openai-agents.md
Labels: documentation, size:XS, auto-merge

#1462 docs(scores): add session level scores changelog
  pages/changelog/2025-04-28-session-level-scores.mdx
Labels: documentation, size:M, auto-merge

#1461 There is a semicolon in the python code
  cookbook/integration_langchain.ipynb
Labels: documentation, size:XS

#1463 chore: add hipaa to pricing and security pages
  components/home/Pricing.tsx
  components/home/Security.tsx
  components/home/security/hipaa.svg
  pages/docs/data-security-privacy.mdx
Labels: documentation, size:M, auto-merge

#1465 docs: add session scores support to data model docs
  pages/docs/scores/data-model.mdx
Labels: docs, size:S, auto-merge

#1466 docs: update pydantic AI notebook
  cookbook/integration_pydantic_ai.ipynb
  pages/docs/integrations/openaiagentssdk/openai-agents.md
  pages/docs/integrations/pydantic-ai.md
  pages/guides/cookbook/integration_openai-agents.md
  pages/guides/cookbook/integration_pydantic_ai.md
Labels: docs, size:S, auto-merge

#1468 docs: update community hour banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1469 docs: remove banner
  theme.config.tsx
Labels: docs, size:S, auto-merge

#1470 docs: add april update to blog
  pages/blog/2025-04-30-langfuse-april-update.mdx
  public/images/blog/2025-04-30-langfuse-april-update/10k-github-stars.png
  public/images/blog/2025-04-30-langfuse-april-update/april-update.png
  public/images/blog/2025-04-30-langfuse-april-update/hipaa.png
  public/images/blog/2025-04-30-langfuse-april-update/protected-prompt-labels.png
  public/images/blog/2025-04-30-langfuse-april-update/session-level-scores.png
  public/images/blog/2025-04-30-langfuse-april-update/tool-call-playground.png
Labels: documentation, size:M, auto-merge
